export type SetupAction =
  | { type: 'navigate'; url: string }
  | { type: 'click'; selector: string }
  | { type: 'fill'; selector: string; value: string }
  | { type: 'wait'; ms: number }
  | { type: 'setRole'; role: 'brand' | 'influencer' }
  | { type: 'waitForSelector'; selector: string; timeout?: number };

export interface ScreenshotSpec {
  id: string;
  storyId: string;
  pageTitle: string;
  route: string;
  roleContext: 'brand' | 'influencer' | 'none';
  state: string;
  viewport: { width: number; height: number };
  setupActions?: SetupAction[];
  waitFor?: string;
  subdir: string;
}

const DEFAULT_VIEWPORT = { width: 1440, height: 900 };

export const SCREENSHOTS: ScreenshotSpec[] = [
  // ─────────────────────────────────────────────────────────────
  // SHARED (6)
  // ─────────────────────────────────────────────────────────────
  {
    id: 'SCR-S-UTIL-1',
    storyId: 'S-UTIL-1',
    pageTitle: 'Role Selection',
    route: '/',
    roleContext: 'none',
    state: 'default',
    viewport: DEFAULT_VIEWPORT,
    subdir: 'shared',
  },
  {
    id: 'SCR-S-UTIL-2',
    storyId: 'S-UTIL-2',
    pageTitle: 'Terms of Service',
    route: '/terms',
    roleContext: 'none',
    state: 'default',
    viewport: DEFAULT_VIEWPORT,
    subdir: 'shared',
  },
  {
    id: 'SCR-S-UTIL-3',
    storyId: 'S-UTIL-3',
    pageTitle: 'Privacy Policy',
    route: '/privacy',
    roleContext: 'none',
    state: 'default',
    viewport: DEFAULT_VIEWPORT,
    subdir: 'shared',
  },
  {
    id: 'SCR-S-UTIL-4',
    storyId: 'S-UTIL-4',
    pageTitle: 'Data Deletion',
    route: '/data-deletion',
    roleContext: 'none',
    state: 'default',
    viewport: DEFAULT_VIEWPORT,
    subdir: 'shared',
  },
  {
    id: 'SCR-S-UTIL-5',
    storyId: 'S-UTIL-5',
    pageTitle: 'Unauthorized',
    route: '/unauthorized',
    roleContext: 'none',
    state: 'default',
    viewport: DEFAULT_VIEWPORT,
    subdir: 'shared',
  },
  {
    id: 'SCR-S-UTIL-6',
    storyId: 'S-UTIL-6',
    pageTitle: 'API Documentation',
    route: '/api-docs',
    roleContext: 'none',
    state: 'default',
    viewport: DEFAULT_VIEWPORT,
    subdir: 'shared',
  },

  // ─────────────────────────────────────────────────────────────
  // BRAND AUTH (14)
  // ─────────────────────────────────────────────────────────────
  {
    id: 'SCR-B-AUTH-1',
    storyId: 'B-AUTH-1',
    pageTitle: 'Brand Welcome',
    route: '/auth/brand/welcome',
    roleContext: 'none',
    state: 'default',
    viewport: DEFAULT_VIEWPORT,
    subdir: 'brand/auth',
  },
  {
    id: 'SCR-B-AUTH-2',
    storyId: 'B-AUTH-2',
    pageTitle: 'Brand Login',
    route: '/auth/brand/login',
    roleContext: 'none',
    state: 'default',
    viewport: DEFAULT_VIEWPORT,
    subdir: 'brand/auth',
  },
  {
    id: 'SCR-B-AUTH-4-S1',
    storyId: 'B-AUTH-4',
    pageTitle: 'Brand Signup - Account',
    route: '/auth/brand/signup/account',
    roleContext: 'none',
    state: 'step-1',
    viewport: DEFAULT_VIEWPORT,
    subdir: 'brand/auth',
  },
  {
    id: 'SCR-B-AUTH-4-S2',
    storyId: 'B-AUTH-4',
    pageTitle: 'Brand Signup - Company',
    route: '/auth/brand/signup/company',
    roleContext: 'none',
    state: 'step-2',
    viewport: DEFAULT_VIEWPORT,
    subdir: 'brand/auth',
  },
  {
    id: 'SCR-B-AUTH-4-S3',
    storyId: 'B-AUTH-4',
    pageTitle: 'Brand Signup - Social',
    route: '/auth/brand/signup/social',
    roleContext: 'none',
    state: 'step-3',
    viewport: DEFAULT_VIEWPORT,
    subdir: 'brand/auth',
  },
  {
    id: 'SCR-B-AUTH-4-SUCCESS',
    storyId: 'B-AUTH-4',
    pageTitle: 'Brand Signup - Success',
    route: '/auth/brand/signup/success',
    roleContext: 'none',
    state: 'success',
    viewport: DEFAULT_VIEWPORT,
    subdir: 'brand/auth',
  },
  {
    id: 'SCR-B-AUTH-5-VERIFY',
    storyId: 'B-AUTH-5',
    pageTitle: 'Brand Verify Email',
    route: '/auth/brand/signup/verify-email',
    roleContext: 'none',
    state: 'default',
    viewport: DEFAULT_VIEWPORT,
    subdir: 'brand/auth',
  },
  {
    id: 'SCR-B-AUTH-5-VERIFIED',
    storyId: 'B-AUTH-5',
    pageTitle: 'Brand Email Verified',
    route: '/auth/brand/signup/email-verified',
    roleContext: 'none',
    state: 'verified',
    viewport: DEFAULT_VIEWPORT,
    subdir: 'brand/auth',
  },
  {
    id: 'SCR-B-AUTH-6-FORGOT',
    storyId: 'B-AUTH-6',
    pageTitle: 'Brand Forgot Password',
    route: '/auth/brand/forgot-password',
    roleContext: 'none',
    state: 'default',
    viewport: DEFAULT_VIEWPORT,
    subdir: 'brand/auth',
  },
  {
    id: 'SCR-B-AUTH-6-CODE',
    storyId: 'B-AUTH-6',
    pageTitle: 'Brand Verify Code',
    route: '/auth/brand/verify-code',
    roleContext: 'none',
    state: 'default',
    viewport: DEFAULT_VIEWPORT,
    subdir: 'brand/auth',
  },
  {
    id: 'SCR-B-AUTH-6-RESET',
    storyId: 'B-AUTH-6',
    pageTitle: 'Brand Reset Password',
    route: '/auth/brand/reset-password',
    roleContext: 'none',
    state: 'default',
    viewport: DEFAULT_VIEWPORT,
    subdir: 'brand/auth',
  },
  {
    id: 'SCR-B-AUTH-6-SUCCESS',
    storyId: 'B-AUTH-6',
    pageTitle: 'Brand Reset Success',
    route: '/auth/brand/reset-success',
    roleContext: 'none',
    state: 'success',
    viewport: DEFAULT_VIEWPORT,
    subdir: 'brand/auth',
  },
  {
    id: 'SCR-B-AUTH-8',
    storyId: 'B-AUTH-8',
    pageTitle: 'Brand Complete Profile',
    route: '/auth/brand/complete-profile',
    roleContext: 'none',
    state: 'default',
    viewport: DEFAULT_VIEWPORT,
    subdir: 'brand/auth',
  },
  {
    id: 'SCR-B-AUTH-7',
    storyId: 'B-AUTH-7',
    pageTitle: 'Email Verification Handler',
    route: '/auth/action',
    roleContext: 'none',
    state: 'default',
    viewport: DEFAULT_VIEWPORT,
    subdir: 'brand/auth',
  },

  // ─────────────────────────────────────────────────────────────
  // INFLUENCER AUTH (12)
  // ─────────────────────────────────────────────────────────────
  {
    id: 'SCR-I-AUTH-1',
    storyId: 'I-AUTH-1',
    // Note: /auth/influencer/welcome may not exist; falls back to /auth/influencer/login
    pageTitle: 'Influencer Welcome',
    route: '/auth/influencer/welcome',
    roleContext: 'none',
    state: 'default',
    viewport: DEFAULT_VIEWPORT,
    subdir: 'influencer/auth',
  },
  {
    id: 'SCR-I-AUTH-2',
    storyId: 'I-AUTH-2',
    pageTitle: 'Influencer Login',
    route: '/auth/influencer/login',
    roleContext: 'none',
    state: 'default',
    viewport: DEFAULT_VIEWPORT,
    subdir: 'influencer/auth',
  },
  {
    id: 'SCR-I-AUTH-4',
    storyId: 'I-AUTH-4',
    pageTitle: 'Influencer Signup',
    route: '/auth/influencer/signup/email',
    roleContext: 'none',
    state: 'default',
    viewport: DEFAULT_VIEWPORT,
    subdir: 'influencer/auth',
  },
  {
    id: 'SCR-I-AUTH-5-VERIFY',
    storyId: 'I-AUTH-5',
    pageTitle: 'Influencer Verify Email',
    route: '/auth/influencer/signup/verify-email',
    roleContext: 'none',
    state: 'default',
    viewport: DEFAULT_VIEWPORT,
    subdir: 'influencer/auth',
  },
  {
    id: 'SCR-I-AUTH-5-VERIFIED',
    storyId: 'I-AUTH-5',
    pageTitle: 'Influencer Email Verified',
    route: '/auth/influencer/signup/email-verified',
    roleContext: 'none',
    state: 'verified',
    viewport: DEFAULT_VIEWPORT,
    subdir: 'influencer/auth',
  },
  {
    id: 'SCR-I-AUTH-6-SOCIAL',
    storyId: 'I-AUTH-6',
    pageTitle: 'Influencer Social Verify',
    route: '/auth/influencer/verify/social',
    roleContext: 'none',
    state: 'default',
    viewport: DEFAULT_VIEWPORT,
    subdir: 'influencer/auth',
  },
  {
    id: 'SCR-I-AUTH-6-SUCCESS',
    storyId: 'I-AUTH-6',
    pageTitle: 'Influencer Verify Success',
    route: '/auth/influencer/verify/success',
    roleContext: 'none',
    state: 'success',
    viewport: DEFAULT_VIEWPORT,
    subdir: 'influencer/auth',
  },
  {
    id: 'SCR-I-AUTH-7-FORGOT',
    storyId: 'I-AUTH-7',
    pageTitle: 'Influencer Forgot Password',
    route: '/auth/influencer/forgot-password',
    roleContext: 'none',
    state: 'default',
    viewport: DEFAULT_VIEWPORT,
    subdir: 'influencer/auth',
  },
  {
    id: 'SCR-I-AUTH-7-RESET',
    storyId: 'I-AUTH-7',
    pageTitle: 'Influencer Reset Password',
    route: '/auth/influencer/reset-password',
    roleContext: 'none',
    state: 'default',
    viewport: DEFAULT_VIEWPORT,
    subdir: 'influencer/auth',
  },
  {
    id: 'SCR-I-AUTH-7-SUCCESS',
    storyId: 'I-AUTH-7',
    pageTitle: 'Influencer Reset Success',
    route: '/auth/influencer/reset-success',
    roleContext: 'none',
    state: 'success',
    viewport: DEFAULT_VIEWPORT,
    subdir: 'influencer/auth',
  },
  {
    id: 'SCR-I-AUTH-8',
    storyId: 'I-AUTH-8',
    pageTitle: 'Influencer Complete Profile',
    route: '/auth/influencer/complete-profile',
    roleContext: 'none',
    state: 'default',
    viewport: DEFAULT_VIEWPORT,
    subdir: 'influencer/auth',
  },
  {
    id: 'SCR-I-AUTH-EXT',
    storyId: 'I-AUTH-6',
    pageTitle: 'External Auth Prompt',
    route: '/auth/influencer/external-auth',
    roleContext: 'none',
    state: 'default',
    viewport: DEFAULT_VIEWPORT,
    subdir: 'influencer/auth',
  },

  // ─────────────────────────────────────────────────────────────
  // BRAND DASHBOARD (2)
  // ─────────────────────────────────────────────────────────────
  {
    id: 'SCR-B-DASH-1',
    storyId: 'B-DASH-1',
    pageTitle: 'Brand Dashboard',
    route: '/brands/dashboard',
    roleContext: 'brand',
    state: 'default',
    viewport: DEFAULT_VIEWPORT,
    subdir: 'brand/dashboard',
  },
  {
    id: 'SCR-B-DASH-4',
    storyId: 'B-DASH-4',
    pageTitle: 'Brand Dashboard - Recommendations',
    route: '/brands/dashboard',
    roleContext: 'brand',
    state: 'scrolled',
    viewport: DEFAULT_VIEWPORT,
    setupActions: [{ type: 'wait', ms: 1000 }],
    subdir: 'brand/dashboard',
  },

  // ─────────────────────────────────────────────────────────────
  // BRAND DISCOVERY (5)
  // ─────────────────────────────────────────────────────────────
  {
    id: 'SCR-B-DISC-1',
    storyId: 'B-DISC-1',
    pageTitle: 'Discovery Home',
    route: '/brands/discover',
    roleContext: 'brand',
    state: 'default',
    viewport: DEFAULT_VIEWPORT,
    subdir: 'brand/discovery',
  },
  {
    id: 'SCR-B-DISC-2',
    storyId: 'B-DISC-2',
    pageTitle: 'Discovery - Topic Mode',
    route: '/brands/discover',
    roleContext: 'brand',
    state: 'topic-mode',
    viewport: DEFAULT_VIEWPORT,
    subdir: 'brand/discovery',
  },
  {
    id: 'SCR-B-DISC-4',
    storyId: 'B-DISC-4',
    pageTitle: 'Discovery Results',
    route: '/brands/discover/results?query=fashion&platforms=instagram',
    roleContext: 'brand',
    state: 'default',
    viewport: DEFAULT_VIEWPORT,
    subdir: 'brand/discovery',
  },
  {
    id: 'SCR-B-DISC-6-LIST',
    storyId: 'B-DISC-6',
    pageTitle: 'Discovery Results - List View',
    route: '/brands/discover/results?query=fashion&platforms=instagram',
    roleContext: 'brand',
    state: 'list-view',
    viewport: DEFAULT_VIEWPORT,
    subdir: 'brand/discovery',
  },
  {
    id: 'SCR-B-DISC-9',
    storyId: 'B-DISC-9',
    pageTitle: 'Discovery - Topics',
    route: '/brands/discover',
    roleContext: 'brand',
    state: 'topics-expanded',
    viewport: DEFAULT_VIEWPORT,
    subdir: 'brand/discovery',
  },

  // ─────────────────────────────────────────────────────────────
  // BRAND CAMPAIGNS (12)
  // ─────────────────────────────────────────────────────────────
  {
    id: 'SCR-B-CAMP-1',
    storyId: 'B-CAMP-1',
    pageTitle: 'Campaign List',
    route: '/brands/campaigns',
    roleContext: 'brand',
    state: 'default',
    viewport: DEFAULT_VIEWPORT,
    subdir: 'brand/campaigns',
  },
  {
    id: 'SCR-B-CAMP-2-S1',
    storyId: 'B-CAMP-2',
    pageTitle: 'Campaign Create - Step 1',
    route: '/brands/campaigns/create',
    roleContext: 'brand',
    state: 'step-1',
    viewport: DEFAULT_VIEWPORT,
    subdir: 'brand/campaigns',
  },
  {
    id: 'SCR-B-CAMP-2-S2',
    storyId: 'B-CAMP-2',
    pageTitle: 'Campaign Create - Step 2',
    route: '/brands/campaigns/create',
    roleContext: 'brand',
    state: 'step-2',
    viewport: DEFAULT_VIEWPORT,
    subdir: 'brand/campaigns',
  },
  {
    id: 'SCR-B-CAMP-2-S3',
    storyId: 'B-CAMP-2',
    pageTitle: 'Campaign Create - Step 3',
    route: '/brands/campaigns/create',
    roleContext: 'brand',
    state: 'step-3',
    viewport: DEFAULT_VIEWPORT,
    subdir: 'brand/campaigns',
  },
  {
    id: 'SCR-B-CAMP-2-S4',
    storyId: 'B-CAMP-2',
    pageTitle: 'Campaign Create - Step 4',
    route: '/brands/campaigns/create',
    roleContext: 'brand',
    state: 'step-4',
    viewport: DEFAULT_VIEWPORT,
    subdir: 'brand/campaigns',
  },
  {
    id: 'SCR-B-CAMP-2-S5',
    storyId: 'B-CAMP-2',
    pageTitle: 'Campaign Create - Step 5',
    route: '/brands/campaigns/create',
    roleContext: 'brand',
    state: 'step-5',
    viewport: DEFAULT_VIEWPORT,
    subdir: 'brand/campaigns',
  },
  {
    id: 'SCR-B-CAMP-2-S6',
    storyId: 'B-CAMP-2',
    pageTitle: 'Campaign Create - Step 6',
    route: '/brands/campaigns/create',
    roleContext: 'brand',
    state: 'step-6',
    viewport: DEFAULT_VIEWPORT,
    subdir: 'brand/campaigns',
  },
  {
    id: 'SCR-B-CAMP-4-OVERVIEW',
    storyId: 'B-CAMP-4',
    pageTitle: 'Campaign Dashboard - Overview',
    route: '/brands/campaigns/mock-campaign-1/dashboard',
    roleContext: 'brand',
    state: 'overview-tab',
    viewport: DEFAULT_VIEWPORT,
    subdir: 'brand/campaigns',
  },
  {
    id: 'SCR-B-CAMP-4-CREATORS',
    storyId: 'B-CAMP-4',
    pageTitle: 'Campaign Dashboard - Creators',
    route: '/brands/campaigns/mock-campaign-1/dashboard',
    roleContext: 'brand',
    state: 'creators-tab',
    viewport: DEFAULT_VIEWPORT,
    subdir: 'brand/campaigns',
  },
  {
    id: 'SCR-B-CAMP-4-CONTENT',
    storyId: 'B-CAMP-4',
    pageTitle: 'Campaign Dashboard - Content',
    route: '/brands/campaigns/mock-campaign-1/dashboard',
    roleContext: 'brand',
    state: 'content-tab',
    viewport: DEFAULT_VIEWPORT,
    subdir: 'brand/campaigns',
  },
  {
    id: 'SCR-B-CAMP-4-ANALYTICS',
    storyId: 'B-CAMP-4',
    pageTitle: 'Campaign Dashboard - Analytics',
    route: '/brands/campaigns/mock-campaign-1/dashboard',
    roleContext: 'brand',
    state: 'analytics-tab',
    viewport: DEFAULT_VIEWPORT,
    subdir: 'brand/campaigns',
  },
  {
    id: 'SCR-B-CAMP-6',
    storyId: 'B-CAMP-6',
    pageTitle: 'Edit Campaign',
    route: '/brands/campaigns/mock-campaign-1/edit',
    roleContext: 'brand',
    state: 'default',
    viewport: DEFAULT_VIEWPORT,
    subdir: 'brand/campaigns',
  },

  // ─────────────────────────────────────────────────────────────
  // BRAND CREATORS (4)
  // ─────────────────────────────────────────────────────────────
  {
    id: 'SCR-B-CREAT-1',
    storyId: 'B-CREAT-1',
    pageTitle: 'My Creators',
    route: '/brands/influencers',
    roleContext: 'brand',
    state: 'default',
    viewport: DEFAULT_VIEWPORT,
    subdir: 'brand/creators',
  },
  {
    id: 'SCR-B-CREAT-2',
    storyId: 'B-CREAT-2',
    pageTitle: 'My Lists',
    route: '/brands/influencers',
    roleContext: 'brand',
    state: 'lists-tab',
    viewport: DEFAULT_VIEWPORT,
    subdir: 'brand/creators',
  },
  {
    id: 'SCR-B-CREAT-4',
    storyId: 'B-CREAT-4',
    pageTitle: 'Suggestions',
    route: '/brands/influencers',
    roleContext: 'brand',
    state: 'suggestions-tab',
    viewport: DEFAULT_VIEWPORT,
    subdir: 'brand/creators',
  },
  {
    id: 'SCR-B-CREAT-7',
    storyId: 'B-CREAT-7',
    pageTitle: 'Creator Bookmarked',
    route: '/brands/influencers',
    roleContext: 'brand',
    state: 'starred',
    viewport: DEFAULT_VIEWPORT,
    subdir: 'brand/creators',
  },

  // ─────────────────────────────────────────────────────────────
  // BRAND PROFILE (5)
  // ─────────────────────────────────────────────────────────────
  {
    id: 'SCR-B-PROF-1',
    storyId: 'B-PROF-1',
    pageTitle: 'Creator Profile - Overview',
    route: '/brands/influencers/mock-influencer-1',
    roleContext: 'brand',
    state: 'overview-tab',
    viewport: DEFAULT_VIEWPORT,
    subdir: 'brand/profile',
  },
  {
    id: 'SCR-B-PROF-2',
    storyId: 'B-PROF-2',
    pageTitle: 'Creator Profile - Content',
    route: '/brands/influencers/mock-influencer-1',
    roleContext: 'brand',
    state: 'content-tab',
    viewport: DEFAULT_VIEWPORT,
    subdir: 'brand/profile',
  },
  {
    id: 'SCR-B-PROF-3',
    storyId: 'B-PROF-3',
    pageTitle: 'Creator Profile - Demographics',
    route: '/brands/influencers/mock-influencer-1',
    roleContext: 'brand',
    state: 'demographics-tab',
    viewport: DEFAULT_VIEWPORT,
    subdir: 'brand/profile',
  },
  {
    id: 'SCR-B-PROF-4',
    storyId: 'B-PROF-4',
    pageTitle: 'Creator Profile - Analytics',
    route: '/brands/influencers/mock-influencer-1',
    roleContext: 'brand',
    state: 'analytics-tab',
    viewport: DEFAULT_VIEWPORT,
    subdir: 'brand/profile',
  },
  {
    id: 'SCR-B-SETT-1',
    storyId: 'B-SETT-1',
    pageTitle: 'Brand Profile Settings',
    route: '/brands/profile',
    roleContext: 'brand',
    state: 'default',
    viewport: DEFAULT_VIEWPORT,
    subdir: 'brand/profile',
  },

  // ─────────────────────────────────────────────────────────────
  // BRAND NOTIFICATIONS + ANALYTICS (4)
  // ─────────────────────────────────────────────────────────────
  {
    id: 'SCR-B-NOTIF-1',
    storyId: 'B-NOTIF-1',
    pageTitle: 'Brand Notifications',
    route: '/brands/notifications',
    roleContext: 'brand',
    state: 'default',
    viewport: DEFAULT_VIEWPORT,
    subdir: 'brand/notifications',
  },
  {
    id: 'SCR-B-NOTIF-2',
    storyId: 'B-NOTIF-2',
    pageTitle: 'Brand Notifications - Unread',
    route: '/brands/notifications',
    roleContext: 'brand',
    state: 'unread-filter',
    viewport: DEFAULT_VIEWPORT,
    subdir: 'brand/notifications',
  },
  {
    id: 'SCR-B-ANAL-1',
    storyId: 'B-ANAL-1',
    pageTitle: 'Brand Analytics',
    route: '/brands/analytics',
    roleContext: 'brand',
    state: 'default',
    viewport: DEFAULT_VIEWPORT,
    subdir: 'brand/analytics',
  },
  {
    id: 'SCR-B-ANAL-2',
    storyId: 'B-ANAL-2',
    pageTitle: 'Brand Saved Reports',
    route: '/brands/analytics',
    roleContext: 'brand',
    state: 'saved-reports-tab',
    viewport: DEFAULT_VIEWPORT,
    subdir: 'brand/analytics',
  },

  // ─────────────────────────────────────────────────────────────
  // INFLUENCER DASHBOARD (2)
  // ─────────────────────────────────────────────────────────────
  {
    id: 'SCR-I-DASH-1',
    storyId: 'I-DASH-1',
    pageTitle: 'Influencer Dashboard',
    route: '/influencers',
    roleContext: 'influencer',
    state: 'default',
    viewport: DEFAULT_VIEWPORT,
    subdir: 'influencer/dashboard',
  },
  {
    id: 'SCR-I-DASH-4',
    storyId: 'I-DASH-4',
    pageTitle: 'Influencer Dashboard - Recommendations',
    route: '/influencers',
    roleContext: 'influencer',
    state: 'scrolled',
    viewport: DEFAULT_VIEWPORT,
    subdir: 'influencer/dashboard',
  },

  // ─────────────────────────────────────────────────────────────
  // INFLUENCER MARKETPLACE (6)
  // ─────────────────────────────────────────────────────────────
  {
    id: 'SCR-I-MKTPL-1',
    storyId: 'I-MKTPL-1',
    pageTitle: 'Marketplace',
    route: '/influencers/marketplace',
    roleContext: 'influencer',
    state: 'default',
    viewport: DEFAULT_VIEWPORT,
    subdir: 'influencer/marketplace',
  },
  {
    id: 'SCR-I-MKTPL-2',
    storyId: 'I-MKTPL-2',
    pageTitle: 'Marketplace - Filtered',
    route: '/influencers/marketplace',
    roleContext: 'influencer',
    state: 'filtered',
    viewport: DEFAULT_VIEWPORT,
    subdir: 'influencer/marketplace',
  },
  {
    id: 'SCR-I-MKTPL-3',
    storyId: 'I-MKTPL-3',
    pageTitle: 'Marketplace - Search',
    route: '/influencers/marketplace/search',
    roleContext: 'influencer',
    state: 'default',
    viewport: DEFAULT_VIEWPORT,
    subdir: 'influencer/marketplace',
  },
  {
    id: 'SCR-I-MKTPL-5',
    storyId: 'I-MKTPL-5',
    pageTitle: 'Campaign Brief',
    route: '/influencers/marketplace/mock-campaign-1',
    roleContext: 'influencer',
    state: 'default',
    viewport: DEFAULT_VIEWPORT,
    subdir: 'influencer/marketplace',
  },
  {
    id: 'SCR-I-MKTPL-6-MODAL',
    storyId: 'I-MKTPL-6',
    pageTitle: 'Application Modal',
    route: '/influencers/marketplace/mock-campaign-1',
    roleContext: 'influencer',
    state: 'modal-open',
    viewport: DEFAULT_VIEWPORT,
    subdir: 'influencer/marketplace',
  },
  {
    id: 'SCR-I-MKTPL-7-SUCCESS',
    storyId: 'I-MKTPL-7',
    pageTitle: 'Application Success',
    route: '/influencers/marketplace/mock-campaign-1',
    roleContext: 'influencer',
    state: 'success-modal',
    viewport: DEFAULT_VIEWPORT,
    subdir: 'influencer/marketplace',
  },

  // ─────────────────────────────────────────────────────────────
  // INFLUENCER CAMPAIGNS (8)
  // ─────────────────────────────────────────────────────────────
  {
    id: 'SCR-I-CAMP-1',
    storyId: 'I-CAMP-1',
    pageTitle: 'My Campaigns',
    route: '/influencers/campaigns',
    roleContext: 'influencer',
    state: 'default',
    viewport: DEFAULT_VIEWPORT,
    subdir: 'influencer/campaigns',
  },
  {
    id: 'SCR-I-CAMP-2-OVERVIEW',
    storyId: 'I-CAMP-2',
    pageTitle: 'Campaign - Overview',
    route: '/influencers/campaigns/mock-campaign-1',
    roleContext: 'influencer',
    state: 'overview-tab',
    viewport: DEFAULT_VIEWPORT,
    subdir: 'influencer/campaigns',
  },
  {
    id: 'SCR-I-CAMP-2-CONTENT',
    storyId: 'I-CAMP-2',
    pageTitle: 'Campaign - Content',
    route: '/influencers/campaigns/mock-campaign-1',
    roleContext: 'influencer',
    state: 'content-tab',
    viewport: DEFAULT_VIEWPORT,
    subdir: 'influencer/campaigns',
  },
  {
    id: 'SCR-I-CAMP-2-BRIEF',
    storyId: 'I-CAMP-2',
    pageTitle: 'Campaign - Brief',
    route: '/influencers/campaigns/mock-campaign-1',
    roleContext: 'influencer',
    state: 'brief-tab',
    viewport: DEFAULT_VIEWPORT,
    subdir: 'influencer/campaigns',
  },
  {
    id: 'SCR-I-CAMP-2-PAYMENTS',
    storyId: 'I-CAMP-2',
    pageTitle: 'Campaign - Payments',
    route: '/influencers/campaigns/mock-campaign-1',
    roleContext: 'influencer',
    state: 'payments-tab',
    viewport: DEFAULT_VIEWPORT,
    subdir: 'influencer/campaigns',
  },
  {
    id: 'SCR-I-CAMP-2-ANALYTICS',
    storyId: 'I-CAMP-2',
    pageTitle: 'Campaign - Analytics',
    route: '/influencers/campaigns/mock-campaign-1',
    roleContext: 'influencer',
    state: 'analytics-tab',
    viewport: DEFAULT_VIEWPORT,
    subdir: 'influencer/campaigns',
  },
  {
    id: 'SCR-I-CAMP-3',
    storyId: 'I-CAMP-3',
    pageTitle: 'Content Submission',
    route: '/influencers/campaigns/mock-campaign-1/submit-content',
    roleContext: 'influencer',
    state: 'default',
    viewport: DEFAULT_VIEWPORT,
    subdir: 'influencer/campaigns',
  },
  {
    id: 'SCR-I-CAMP-5',
    storyId: 'I-CAMP-5',
    pageTitle: 'Saved Campaigns',
    route: '/influencers/campaigns',
    roleContext: 'influencer',
    state: 'saved-tab',
    viewport: DEFAULT_VIEWPORT,
    subdir: 'influencer/campaigns',
  },

  // ─────────────────────────────────────────────────────────────
  // INFLUENCER APPLICATIONS (3)
  // ─────────────────────────────────────────────────────────────
  {
    id: 'SCR-I-APP-1',
    storyId: 'I-APP-1',
    pageTitle: 'Applications',
    route: '/influencers/campaign-applications',
    roleContext: 'influencer',
    state: 'default',
    viewport: DEFAULT_VIEWPORT,
    subdir: 'influencer/applications',
  },
  {
    id: 'SCR-I-APP-2',
    storyId: 'I-APP-2',
    pageTitle: 'Applications - Filtered',
    route: '/influencers/campaign-applications',
    roleContext: 'influencer',
    state: 'status-filter',
    viewport: DEFAULT_VIEWPORT,
    subdir: 'influencer/applications',
  },
  {
    id: 'SCR-I-APP-4',
    storyId: 'I-APP-4',
    pageTitle: 'Withdrawal Modal',
    route: '/influencers/campaign-applications',
    roleContext: 'influencer',
    state: 'withdrawal-modal',
    viewport: DEFAULT_VIEWPORT,
    subdir: 'influencer/applications',
  },

  // ─────────────────────────────────────────────────────────────
  // INFLUENCER INVITATIONS (2)
  // ─────────────────────────────────────────────────────────────
  {
    id: 'SCR-I-INV-1',
    storyId: 'I-INV-1',
    pageTitle: 'Invitations',
    route: '/influencers/invitations',
    roleContext: 'influencer',
    state: 'default',
    viewport: DEFAULT_VIEWPORT,
    subdir: 'influencer/invitations',
  },
  {
    id: 'SCR-I-INV-2',
    storyId: 'I-INV-2',
    pageTitle: 'Invitation Accept/Decline',
    route: '/influencers/invitations',
    roleContext: 'influencer',
    state: 'action-state',
    viewport: DEFAULT_VIEWPORT,
    subdir: 'influencer/invitations',
  },

  // ─────────────────────────────────────────────────────────────
  // INFLUENCER PROFILE (2)
  // ─────────────────────────────────────────────────────────────
  {
    id: 'SCR-I-PROF-1',
    storyId: 'I-PROF-1',
    pageTitle: 'Influencer Profile - Overview',
    route: '/influencers/profile',
    roleContext: 'influencer',
    state: 'default',
    viewport: DEFAULT_VIEWPORT,
    subdir: 'influencer/profile',
  },
  {
    id: 'SCR-I-PROF-2',
    storyId: 'I-PROF-2',
    pageTitle: 'Influencer Profile - Settings',
    route: '/influencers/profile',
    roleContext: 'influencer',
    state: 'settings-tab',
    viewport: DEFAULT_VIEWPORT,
    subdir: 'influencer/profile',
  },

  // ─────────────────────────────────────────────────────────────
  // INFLUENCER NOTIFICATIONS (2)
  // ─────────────────────────────────────────────────────────────
  {
    id: 'SCR-I-NOTIF-1',
    storyId: 'I-NOTIF-1',
    pageTitle: 'Influencer Notifications',
    route: '/influencers/notifications',
    roleContext: 'influencer',
    state: 'default',
    viewport: DEFAULT_VIEWPORT,
    subdir: 'influencer/notifications',
  },
  {
    id: 'SCR-I-NOTIF-2',
    storyId: 'I-NOTIF-2',
    pageTitle: 'Influencer Notifications - Unread',
    route: '/influencers/notifications',
    roleContext: 'influencer',
    state: 'unread-filter',
    viewport: DEFAULT_VIEWPORT,
    subdir: 'influencer/notifications',
  },

  // ─────────────────────────────────────────────────────────────
  // INFLUENCER CALENDAR (1)
  // ─────────────────────────────────────────────────────────────
  {
    id: 'SCR-I-CAL-1',
    storyId: 'I-CAL-1',
    pageTitle: 'Calendar',
    route: '/influencers/calendar',
    roleContext: 'influencer',
    state: 'default',
    viewport: DEFAULT_VIEWPORT,
    subdir: 'influencer/calendar',
  },

  // ─────────────────────────────────────────────────────────────
  // INFLUENCER CONTENT (1)
  // ─────────────────────────────────────────────────────────────
  {
    id: 'SCR-I-CONT-1',
    storyId: 'I-CONT-1',
    pageTitle: 'Content Submission',
    route: '/influencers/campaigns/mock-campaign-1/submit-content',
    roleContext: 'influencer',
    state: 'default',
    viewport: DEFAULT_VIEWPORT,
    subdir: 'influencer/campaigns',
  },
];

export const getScreenshotsByStory = (storyId: string): ScreenshotSpec[] =>
  SCREENSHOTS.filter((s) => s.storyId === storyId);
