// HeyCreator Platform — User Story Registry
// Source of truth for all user stories across Brand, Influencer, and Shared roles.
// Generated from USER_STORIES_AND_FEATURES.md

export type StoryStatus = 'DONE' | 'PARTIAL' | 'PLACEHOLDER';
export type StoryRole = 'Brand' | 'Influencer' | 'Shared';

export interface UserStory {
  id: string;
  role: StoryRole;
  module: string;
  moduleCode: string;
  story: string;
  status: StoryStatus;
  routes: string[];
  apiEndpoints: string[];
  components: string[];
  screenshotIds: string[];
  notes: string;
  versionAdded: string;
}

export const STORIES: UserStory[] = [
  // ─────────────────────────────────────────────────────────────────────────────
  // BRAND — Authentication
  // ─────────────────────────────────────────────────────────────────────────────
  {
    id: 'B-AUTH-1',
    role: 'Brand',
    module: 'Authentication',
    moduleCode: 'B-AUTH',
    story: 'Welcome page with feature highlights',
    status: 'DONE',
    routes: ['/auth/brand/welcome'],
    apiEndpoints: [],
    components: ['AuthLayout', 'AuthCard', 'Logo', 'BrandWelcomeCard'],
    screenshotIds: ['SCR-B-AUTH-1'],
    notes: '',
    versionAdded: 'v1.0.0',
  },
  {
    id: 'B-AUTH-2',
    role: 'Brand',
    module: 'Authentication',
    moduleCode: 'B-AUTH',
    story: 'Log in with email/password',
    status: 'DONE',
    routes: ['/auth/brand/login'],
    apiEndpoints: ['Firebase Auth SDK'],
    components: [
      'AuthLayout',
      'AuthCard',
      'InputField',
      'PasswordInputField',
      'PrimaryButton',
      'ErrorMessage',
    ],
    screenshotIds: ['SCR-B-AUTH-2'],
    notes: '',
    versionAdded: 'v1.0.0',
  },
  {
    id: 'B-AUTH-3',
    role: 'Brand',
    module: 'Authentication',
    moduleCode: 'B-AUTH',
    story: 'Log in with Google, Facebook, or Apple',
    status: 'DONE',
    routes: ['/auth/brand/login'],
    apiEndpoints: ['Firebase Auth SDK (OAuth)'],
    components: ['SocialAuthButton'],
    screenshotIds: ['SCR-B-AUTH-3'],
    notes: '',
    versionAdded: 'v1.0.0',
  },
  {
    id: 'B-AUTH-4',
    role: 'Brand',
    module: 'Authentication',
    moduleCode: 'B-AUTH',
    story: 'Sign up with 3-step wizard',
    status: 'DONE',
    routes: [
      '/auth/brand/signup/account',
      '/auth/brand/signup/company',
      '/auth/brand/signup/social',
      '/auth/brand/signup/success',
    ],
    apiEndpoints: ['Firebase Auth SDK', 'Firestore'],
    components: ['LinearProgressBar', 'SelectField', 'InputField'],
    screenshotIds: [
      'SCR-B-AUTH-4-S1',
      'SCR-B-AUTH-4-S2',
      'SCR-B-AUTH-4-S3',
      'SCR-B-AUTH-4-SUCCESS',
    ],
    notes: '',
    versionAdded: 'v1.0.0',
  },
  {
    id: 'B-AUTH-5',
    role: 'Brand',
    module: 'Authentication',
    moduleCode: 'B-AUTH',
    story: 'Verify email after signup',
    status: 'DONE',
    routes: [
      '/auth/brand/signup/verify-email',
      '/auth/brand/signup/email-verified',
    ],
    apiEndpoints: [
      'POST /api/auth/resend-verification',
      'POST /api/auth/check-email-verified',
    ],
    components: [],
    screenshotIds: ['SCR-B-AUTH-5'],
    notes: '',
    versionAdded: 'v1.0.0',
  },
  {
    id: 'B-AUTH-6',
    role: 'Brand',
    module: 'Authentication',
    moduleCode: 'B-AUTH',
    story: 'Reset password via email',
    status: 'DONE',
    routes: [
      '/auth/brand/forgot-password',
      '/auth/brand/verify-code',
      '/auth/brand/reset-password',
      '/auth/brand/reset-success',
    ],
    apiEndpoints: [
      'Firebase Auth SDK',
      'POST /api/auth/get-user-role-by-email',
    ],
    components: ['OTPInput'],
    screenshotIds: [
      'SCR-B-AUTH-6-FORGOT',
      'SCR-B-AUTH-6-CODE',
      'SCR-B-AUTH-6-RESET',
      'SCR-B-AUTH-6-SUCCESS',
    ],
    notes: '',
    versionAdded: 'v1.0.0',
  },
  {
    id: 'B-AUTH-7',
    role: 'Brand',
    module: 'Authentication',
    moduleCode: 'B-AUTH',
    story: 'Redirected after email verification',
    status: 'DONE',
    routes: ['/auth/action'],
    apiEndpoints: ['POST /api/auth/get-user-role-by-email'],
    components: [],
    screenshotIds: ['SCR-B-AUTH-7'],
    notes: '',
    versionAdded: 'v1.0.0',
  },
  {
    id: 'B-AUTH-8',
    role: 'Brand',
    module: 'Authentication',
    moduleCode: 'B-AUTH',
    story: 'Must complete profile before access',
    status: 'DONE',
    routes: ['/auth/brand/complete-profile'],
    apiEndpoints: ['Firestore users + brand_profiles'],
    components: [],
    screenshotIds: ['SCR-B-AUTH-8'],
    notes: '',
    versionAdded: 'v1.0.0',
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // BRAND — Dashboard
  // ─────────────────────────────────────────────────────────────────────────────
  {
    id: 'B-DASH-1',
    role: 'Brand',
    module: 'Dashboard',
    moduleCode: 'B-DASH',
    story:
      'Overview with stats cards (active campaigns, total influencers, budget spent, total reach)',
    status: 'DONE',
    routes: ['/brands/dashboard'],
    apiEndpoints: ['GET /api/campaigns', 'GET /api/dashboard/stats'],
    components: ['CampaignListCard', 'Sidebar', 'UserProfileHeader'],
    screenshotIds: ['SCR-B-DASH-1'],
    notes: '',
    versionAdded: 'v1.0.0',
  },
  {
    id: 'B-DASH-2',
    role: 'Brand',
    module: 'Dashboard',
    moduleCode: 'B-DASH',
    story: 'See top 4 campaigns with progress bars',
    status: 'DONE',
    routes: ['/brands/dashboard'],
    apiEndpoints: ['GET /api/campaigns'],
    components: [],
    screenshotIds: ['SCR-B-DASH-2'],
    notes: '',
    versionAdded: 'v1.0.0',
  },
  {
    id: 'B-DASH-3',
    role: 'Brand',
    module: 'Dashboard',
    moduleCode: 'B-DASH',
    story: 'See pending actions',
    status: 'DONE',
    routes: ['/brands/dashboard'],
    apiEndpoints: ['GET /api/notifications'],
    components: [],
    screenshotIds: ['SCR-B-DASH-3'],
    notes: '',
    versionAdded: 'v1.0.0',
  },
  {
    id: 'B-DASH-4',
    role: 'Brand',
    module: 'Dashboard',
    moduleCode: 'B-DASH',
    story: 'See recommended creators and bookmark/invite them',
    status: 'DONE',
    routes: ['/brands/dashboard'],
    apiEndpoints: [
      'GET /api/dashboard/recommended',
      'PATCH /api/profiles/{id}/star',
    ],
    components: ['RecommendedCreatorCard', 'CampaignSelectionModal'],
    screenshotIds: ['SCR-B-DASH-4'],
    notes: '',
    versionAdded: 'v1.0.0',
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // BRAND — Discovery
  // ─────────────────────────────────────────────────────────────────────────────
  {
    id: 'B-DISC-1',
    role: 'Brand',
    module: 'Discovery',
    moduleCode: 'B-DISC',
    story: 'Search by keyword or topic',
    status: 'DONE',
    routes: ['/brands/discover'],
    apiEndpoints: ['GET /api/dashboard/recommended'],
    components: ['DiscoveryHeader'],
    screenshotIds: ['SCR-B-DISC-1'],
    notes: '',
    versionAdded: 'v1.0.0',
  },
  {
    id: 'B-DISC-2',
    role: 'Brand',
    module: 'Discovery',
    moduleCode: 'B-DISC',
    story: 'Toggle Topic/Keyword search modes',
    status: 'DONE',
    routes: ['/brands/discover'],
    apiEndpoints: [],
    components: ['DiscoveryHeader'],
    screenshotIds: ['SCR-B-DISC-2'],
    notes: '',
    versionAdded: 'v1.0.0',
  },
  {
    id: 'B-DISC-3',
    role: 'Brand',
    module: 'Discovery',
    moduleCode: 'B-DISC',
    story: 'Filter by platform (IG, TT, YT, TW, FB)',
    status: 'DONE',
    routes: ['/brands/discover/results'],
    apiEndpoints: ['POST /api/discover/search/stream'],
    components: [],
    screenshotIds: ['SCR-B-DISC-3'],
    notes: '',
    versionAdded: 'v1.0.0',
  },
  {
    id: 'B-DISC-4',
    role: 'Brand',
    module: 'Discovery',
    moduleCode: 'B-DISC',
    story: 'See streaming progressive SSE results',
    status: 'DONE',
    routes: ['/brands/discover/results'],
    apiEndpoints: ['POST /api/discover/search/stream (SSE)'],
    components: ['ResultsGrid', 'RecommendedCreatorCard'],
    screenshotIds: ['SCR-B-DISC-4'],
    notes: '',
    versionAdded: 'v1.0.0',
  },
  {
    id: 'B-DISC-5',
    role: 'Brand',
    module: 'Discovery',
    moduleCode: 'B-DISC',
    story:
      'Apply secondary filters (followers, engagement, reach, location, verified)',
    status: 'DONE',
    routes: ['/brands/discover/results'],
    apiEndpoints: ['POST /api/discover/search/stream'],
    components: ['SecondaryFilterBar', 'FilterSidebar'],
    screenshotIds: ['SCR-B-DISC-5'],
    notes: '',
    versionAdded: 'v1.0.0',
  },
  {
    id: 'B-DISC-6',
    role: 'Brand',
    module: 'Discovery',
    moduleCode: 'B-DISC',
    story: 'Switch grid/list views, sort by various criteria',
    status: 'DONE',
    routes: ['/brands/discover/results'],
    apiEndpoints: [],
    components: ['ResultsGrid', 'ResultsHeader'],
    screenshotIds: ['SCR-B-DISC-6'],
    notes: '',
    versionAdded: 'v1.0.0',
  },
  {
    id: 'B-DISC-7',
    role: 'Brand',
    module: 'Discovery',
    moduleCode: 'B-DISC',
    story: 'Select multiple creators and coalate into unified profile',
    status: 'DONE',
    routes: ['/brands/discover/results'],
    apiEndpoints: ['POST /api/profiles'],
    components: [],
    screenshotIds: ['SCR-B-DISC-7'],
    notes: '',
    versionAdded: 'v1.0.0',
  },
  {
    id: 'B-DISC-8',
    role: 'Brand',
    module: 'Discovery',
    moduleCode: 'B-DISC',
    story: 'Toggle Live Search for fresh API data',
    status: 'DONE',
    routes: ['/brands/discover/results'],
    apiEndpoints: ['POST /api/discover/search/stream'],
    components: [],
    screenshotIds: ['SCR-B-DISC-8'],
    notes: '',
    versionAdded: 'v1.0.0',
  },
  {
    id: 'B-DISC-9',
    role: 'Brand',
    module: 'Discovery',
    moduleCode: 'B-DISC',
    story: 'Browse top topics',
    status: 'DONE',
    routes: ['/brands/discover'],
    apiEndpoints: [],
    components: ['TopTopicsSection'],
    screenshotIds: ['SCR-B-DISC-9'],
    notes: '',
    versionAdded: 'v1.0.0',
  },
  {
    id: 'B-DISC-10',
    role: 'Brand',
    module: 'Discovery',
    moduleCode: 'B-DISC',
    story: 'Creator profiles auto-save on click',
    status: 'DONE',
    routes: ['/brands/discover/results'],
    apiEndpoints: [
      'POST /api/profiles',
      'POST /api/influencer/{id}/enrichment',
    ],
    components: [],
    screenshotIds: ['SCR-B-DISC-10'],
    notes: '',
    versionAdded: 'v1.0.0',
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // BRAND — Campaigns
  // ─────────────────────────────────────────────────────────────────────────────
  {
    id: 'B-CAMP-1',
    role: 'Brand',
    module: 'Campaigns',
    moduleCode: 'B-CAMP',
    story: 'View all campaigns with search, filters, pagination',
    status: 'DONE',
    routes: ['/brands/campaigns'],
    apiEndpoints: ['GET /api/campaigns'],
    components: ['CampaignListTable'],
    screenshotIds: ['SCR-B-CAMP-1'],
    notes: '',
    versionAdded: 'v1.0.0',
  },
  {
    id: 'B-CAMP-2',
    role: 'Brand',
    module: 'Campaigns',
    moduleCode: 'B-CAMP',
    story: 'Create campaign via 6-step wizard',
    status: 'DONE',
    routes: ['/brands/campaigns/create'],
    apiEndpoints: ['POST /api/campaigns'],
    components: ['Step1-Step6', 'ProgressStepper'],
    screenshotIds: ['SCR-B-CAMP-2'],
    notes: '',
    versionAdded: 'v1.0.0',
  },
  {
    id: 'B-CAMP-3',
    role: 'Brand',
    module: 'Campaigns',
    moduleCode: 'B-CAMP',
    story: 'Upload media/documents to campaign',
    status: 'DONE',
    routes: ['/brands/campaigns/create', '/brands/campaigns/[id]/edit'],
    apiEndpoints: ['POST /api/campaigns/{id}/documents'],
    components: ['FileUploadField', 'DocumentUploadZone'],
    screenshotIds: ['SCR-B-CAMP-3'],
    notes: '',
    versionAdded: 'v1.0.0',
  },
  {
    id: 'B-CAMP-4',
    role: 'Brand',
    module: 'Campaigns',
    moduleCode: 'B-CAMP',
    story: 'View campaign dashboard with 4 tabs',
    status: 'DONE',
    routes: ['/brands/campaigns/[id]/dashboard'],
    apiEndpoints: ['GET /api/campaigns/{id}'],
    components: [
      'TabsNavigation',
      'OverviewTabContent',
      'InfluencersTabContent',
      'ContentTabContent',
      'ReportTabContent',
    ],
    screenshotIds: [
      'SCR-B-CAMP-4-OVERVIEW',
      'SCR-B-CAMP-4-CREATORS',
      'SCR-B-CAMP-4-CONTENT',
      'SCR-B-CAMP-4-ANALYTICS',
    ],
    notes: '',
    versionAdded: 'v1.0.0',
  },
  {
    id: 'B-CAMP-5',
    role: 'Brand',
    module: 'Campaigns',
    moduleCode: 'B-CAMP',
    story: 'Publish draft campaign',
    status: 'DONE',
    routes: ['/brands/campaigns/[id]/dashboard'],
    apiEndpoints: ['POST /api/campaigns/{id}/publish'],
    components: [],
    screenshotIds: ['SCR-B-CAMP-5'],
    notes: '',
    versionAdded: 'v1.0.0',
  },
  {
    id: 'B-CAMP-6',
    role: 'Brand',
    module: 'Campaigns',
    moduleCode: 'B-CAMP',
    story: 'Edit active campaign',
    status: 'DONE',
    routes: ['/brands/campaigns/[id]/edit'],
    apiEndpoints: ['PATCH /api/campaigns/{id}'],
    components: [],
    screenshotIds: ['SCR-B-CAMP-6'],
    notes: '',
    versionAdded: 'v1.0.0',
  },
  {
    id: 'B-CAMP-7',
    role: 'Brand',
    module: 'Campaigns',
    moduleCode: 'B-CAMP',
    story: 'Review creator applications (accept/reject)',
    status: 'DONE',
    routes: ['/brands/campaigns/[id]/dashboard'],
    apiEndpoints: [
      'GET /api/campaigns/{id}/applications',
      'PATCH /api/campaigns/{id}/applications/{appId}',
    ],
    components: [],
    screenshotIds: ['SCR-B-CAMP-7'],
    notes: '',
    versionAdded: 'v1.0.0',
  },
  {
    id: 'B-CAMP-8',
    role: 'Brand',
    module: 'Campaigns',
    moduleCode: 'B-CAMP',
    story: 'Invite specific creators',
    status: 'DONE',
    routes: ['/brands/campaigns/[id]/dashboard'],
    apiEndpoints: ['POST /api/campaigns/{id}/invitations'],
    components: ['InviteCreatorsModal'],
    screenshotIds: ['SCR-B-CAMP-8'],
    notes: '',
    versionAdded: 'v1.0.0',
  },
  {
    id: 'B-CAMP-9',
    role: 'Brand',
    module: 'Campaigns',
    moduleCode: 'B-CAMP',
    story: 'Share campaign link externally',
    status: 'DONE',
    routes: ['/brands/campaigns/[id]/dashboard'],
    apiEndpoints: [],
    components: ['ShareCampaignModal'],
    screenshotIds: ['SCR-B-CAMP-9'],
    notes: '',
    versionAdded: 'v1.0.0',
  },
  {
    id: 'B-CAMP-10',
    role: 'Brand',
    module: 'Campaigns',
    moduleCode: 'B-CAMP',
    story: 'Add screening questions',
    status: 'DONE',
    routes: ['/brands/campaigns/create'],
    apiEndpoints: ['POST /api/campaigns'],
    components: [],
    screenshotIds: ['SCR-B-CAMP-10'],
    notes: '',
    versionAdded: 'v1.0.0',
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // BRAND — My Creators
  // ─────────────────────────────────────────────────────────────────────────────
  {
    id: 'B-CREAT-1',
    role: 'Brand',
    module: 'My Creators',
    moduleCode: 'B-CREAT',
    story: 'View saved creators in searchable grid',
    status: 'DONE',
    routes: ['/brands/influencers'],
    apiEndpoints: ['GET /api/brands/creators/global'],
    components: ['MyCreatorsTabs', 'CreatorCard'],
    screenshotIds: ['SCR-B-CREAT-1'],
    notes: '',
    versionAdded: 'v1.0.0',
  },
  {
    id: 'B-CREAT-2',
    role: 'Brand',
    module: 'My Creators',
    moduleCode: 'B-CREAT',
    story: 'Create custom creator lists',
    status: 'DONE',
    routes: ['/brands/influencers'],
    apiEndpoints: ['POST /api/brands/lists'],
    components: ['CreateListModal'],
    screenshotIds: ['SCR-B-CREAT-2'],
    notes: '',
    versionAdded: 'v1.0.0',
  },
  {
    id: 'B-CREAT-3',
    role: 'Brand',
    module: 'My Creators',
    moduleCode: 'B-CREAT',
    story: 'Add/remove creators from lists',
    status: 'DONE',
    routes: ['/brands/influencers'],
    apiEndpoints: ['POST /api/brands/creators/{id}/lists'],
    components: ['AddToListModal'],
    screenshotIds: ['SCR-B-CREAT-3'],
    notes: '',
    versionAdded: 'v1.0.0',
  },
  {
    id: 'B-CREAT-4',
    role: 'Brand',
    module: 'My Creators',
    moduleCode: 'B-CREAT',
    story: 'View AI-suggested creators',
    status: 'DONE',
    routes: ['/brands/influencers'],
    apiEndpoints: ['GET /api/brands/lists/{id}/suggestions'],
    components: ['SuggestionsTab'],
    screenshotIds: ['SCR-B-CREAT-4'],
    notes: '',
    versionAdded: 'v1.0.0',
  },
  {
    id: 'B-CREAT-5',
    role: 'Brand',
    module: 'My Creators',
    moduleCode: 'B-CREAT',
    story: 'View list-level analytics',
    status: 'DONE',
    routes: ['/brands/influencers'],
    apiEndpoints: ['GET /api/brands/lists/{id}'],
    components: ['ListDetailView'],
    screenshotIds: ['SCR-B-CREAT-5'],
    notes: '',
    versionAdded: 'v1.0.0',
  },
  {
    id: 'B-CREAT-6',
    role: 'Brand',
    module: 'My Creators',
    moduleCode: 'B-CREAT',
    story: 'Export creators as CSV',
    status: 'DONE',
    routes: ['/brands/influencers'],
    apiEndpoints: ['POST /api/brands/creators/export'],
    components: [],
    screenshotIds: ['SCR-B-CREAT-6'],
    notes: '',
    versionAdded: 'v1.0.0',
  },
  {
    id: 'B-CREAT-7',
    role: 'Brand',
    module: 'My Creators',
    moduleCode: 'B-CREAT',
    story: 'Bookmark/star creators from any page',
    status: 'DONE',
    routes: ['multiple'],
    apiEndpoints: ['PATCH /api/profiles/{id}/star'],
    components: [],
    screenshotIds: ['SCR-B-CREAT-7'],
    notes: '',
    versionAdded: 'v1.0.0',
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // BRAND — Profile (Creator Profile Viewer)
  // ─────────────────────────────────────────────────────────────────────────────
  {
    id: 'B-PROF-1',
    role: 'Brand',
    module: 'Profile',
    moduleCode: 'B-PROF',
    story: 'View creator Overview tab',
    status: 'DONE',
    routes: ['/brands/influencers/[id]'],
    apiEndpoints: ['GET /api/influencer/{id}/enrichment'],
    components: [
      'ProfileHeader',
      'ProfileSnapshot',
      'InsightsCard',
      'MetricsTable',
      'ContentGrid',
    ],
    screenshotIds: ['SCR-B-PROF-1'],
    notes: '',
    versionAdded: 'v1.0.0',
  },
  {
    id: 'B-PROF-2',
    role: 'Brand',
    module: 'Profile',
    moduleCode: 'B-PROF',
    story: 'View creator Content tab',
    status: 'DONE',
    routes: ['/brands/influencers/[id]'],
    apiEndpoints: ['GET /api/influencer/{id}/enrichment'],
    components: ['ContentGrid'],
    screenshotIds: ['SCR-B-PROF-2'],
    notes: '',
    versionAdded: 'v1.0.0',
  },
  {
    id: 'B-PROF-3',
    role: 'Brand',
    module: 'Profile',
    moduleCode: 'B-PROF',
    story: 'View estimated audience demographics',
    status: 'DONE',
    routes: ['/brands/influencers/[id]'],
    apiEndpoints: ['GET /api/influencer/{id}/enrichment'],
    components: ['DemographicsSection'],
    screenshotIds: ['SCR-B-PROF-3'],
    notes: '',
    versionAdded: 'v1.0.0',
  },
  {
    id: 'B-PROF-4',
    role: 'Brand',
    module: 'Profile',
    moduleCode: 'B-PROF',
    story: 'View per-platform analytics',
    status: 'DONE',
    routes: ['/brands/influencers/[id]'],
    apiEndpoints: ['GET /api/influencer/{id}/enrichment'],
    components: [],
    screenshotIds: ['SCR-B-PROF-4'],
    notes: '',
    versionAdded: 'v1.0.0',
  },
  {
    id: 'B-PROF-5',
    role: 'Brand',
    module: 'Profile',
    moduleCode: 'B-PROF',
    story: 'Real-time enrichment with stale detection',
    status: 'DONE',
    routes: ['/brands/influencers/[id]'],
    apiEndpoints: [
      'GET /api/influencer/{id}/enrichment',
      'POST /api/influencer/{id}/enrichment',
    ],
    components: ['EnrichmentBanner'],
    screenshotIds: ['SCR-B-PROF-5'],
    notes: '',
    versionAdded: 'v1.0.0',
  },
  {
    id: 'B-PROF-6',
    role: 'Brand',
    module: 'Profile',
    moduleCode: 'B-PROF',
    story: 'View similar creators',
    status: 'DONE',
    routes: ['/brands/influencers/[id]'],
    apiEndpoints: ['GET /api/influencer/{id}/enrichment'],
    components: ['SimilarCreators'],
    screenshotIds: ['SCR-B-PROF-6'],
    notes: '',
    versionAdded: 'v1.0.0',
  },
  {
    id: 'B-PROF-7',
    role: 'Brand',
    module: 'Profile',
    moduleCode: 'B-PROF',
    story: 'Add internal notes',
    status: 'DONE',
    routes: ['/brands/influencers/[id]'],
    apiEndpoints: ['Firestore user_collections'],
    components: ['InternalNotes'],
    screenshotIds: ['SCR-B-PROF-7'],
    notes: '',
    versionAdded: 'v1.0.0',
  },
  {
    id: 'B-PROF-8',
    role: 'Brand',
    module: 'Profile',
    moduleCode: 'B-PROF',
    story: 'Add to campaign or message from profile',
    status: 'DONE',
    routes: ['/brands/influencers/[id]'],
    apiEndpoints: ['POST /api/campaigns/{id}/invitations'],
    components: [],
    screenshotIds: ['SCR-B-PROF-8'],
    notes: '',
    versionAdded: 'v1.0.0',
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // BRAND — Settings
  // ─────────────────────────────────────────────────────────────────────────────
  {
    id: 'B-SETT-1',
    role: 'Brand',
    module: 'Settings',
    moduleCode: 'B-SETT',
    story: 'View company profile',
    status: 'DONE',
    routes: ['/brands/profile'],
    apiEndpoints: ['Firestore brand_profiles'],
    components: [],
    screenshotIds: ['SCR-B-SETT-1'],
    notes: '',
    versionAdded: 'v1.0.0',
  },
  {
    id: 'B-SETT-2',
    role: 'Brand',
    module: 'Settings',
    moduleCode: 'B-SETT',
    story: 'Edit company info',
    status: 'DONE',
    routes: ['/brands/profile'],
    apiEndpoints: ['Firestore users + brand_profiles'],
    components: [],
    screenshotIds: ['SCR-B-SETT-2'],
    notes: '',
    versionAdded: 'v1.0.0',
  },
  {
    id: 'B-SETT-3',
    role: 'Brand',
    module: 'Settings',
    moduleCode: 'B-SETT',
    story: 'See profile completion percentage',
    status: 'DONE',
    routes: ['/brands/profile'],
    apiEndpoints: [],
    components: [],
    screenshotIds: ['SCR-B-SETT-3'],
    notes: '',
    versionAdded: 'v1.0.0',
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // BRAND — Notifications
  // ─────────────────────────────────────────────────────────────────────────────
  {
    id: 'B-NOTIF-1',
    role: 'Brand',
    module: 'Notifications',
    moduleCode: 'B-NOTIF',
    story: 'View all notifications with type-specific icons',
    status: 'DONE',
    routes: ['/brands/notifications'],
    apiEndpoints: ['GET /api/notifications'],
    components: ['NotificationBell'],
    screenshotIds: ['SCR-B-NOTIF-1'],
    notes: '',
    versionAdded: 'v1.0.0',
  },
  {
    id: 'B-NOTIF-2',
    role: 'Brand',
    module: 'Notifications',
    moduleCode: 'B-NOTIF',
    story: 'Filter All/Unread',
    status: 'DONE',
    routes: ['/brands/notifications'],
    apiEndpoints: ['GET /api/notifications'],
    components: [],
    screenshotIds: ['SCR-B-NOTIF-2'],
    notes: '',
    versionAdded: 'v1.0.0',
  },
  {
    id: 'B-NOTIF-3',
    role: 'Brand',
    module: 'Notifications',
    moduleCode: 'B-NOTIF',
    story: 'Mark individual as read',
    status: 'DONE',
    routes: ['/brands/notifications'],
    apiEndpoints: ['PATCH /api/notifications/{id}'],
    components: [],
    screenshotIds: ['SCR-B-NOTIF-3'],
    notes: '',
    versionAdded: 'v1.0.0',
  },
  {
    id: 'B-NOTIF-4',
    role: 'Brand',
    module: 'Notifications',
    moduleCode: 'B-NOTIF',
    story: 'Bulk mark all as read',
    status: 'DONE',
    routes: ['/brands/notifications'],
    apiEndpoints: ['POST /api/notifications/mark-all-read'],
    components: [],
    screenshotIds: ['SCR-B-NOTIF-4'],
    notes: '',
    versionAdded: 'v1.0.0',
  },
  {
    id: 'B-NOTIF-5',
    role: 'Brand',
    module: 'Notifications',
    moduleCode: 'B-NOTIF',
    story: 'Dismiss notifications',
    status: 'DONE',
    routes: ['/brands/notifications'],
    apiEndpoints: ['DELETE /api/notifications/{id}'],
    components: [],
    screenshotIds: ['SCR-B-NOTIF-5'],
    notes: '',
    versionAdded: 'v1.0.0',
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // BRAND — Analytics
  // ─────────────────────────────────────────────────────────────────────────────
  {
    id: 'B-ANAL-1',
    role: 'Brand',
    module: 'Analytics',
    moduleCode: 'B-ANAL',
    story: 'View campaign analytics',
    status: 'PARTIAL',
    routes: ['/brands/analytics'],
    apiEndpoints: [
      'GET /api/campaigns',
      'GET /api/brands/analytics/top-content',
    ],
    components: ['AnalyticsMainContent'],
    screenshotIds: ['SCR-B-ANAL-1'],
    notes: '',
    versionAdded: 'v1.0.0',
  },
  {
    id: 'B-ANAL-2',
    role: 'Brand',
    module: 'Analytics',
    moduleCode: 'B-ANAL',
    story: 'View saved reports',
    status: 'PARTIAL',
    routes: ['/brands/analytics'],
    apiEndpoints: [],
    components: ['SavedReportsTabContent'],
    screenshotIds: ['SCR-B-ANAL-2'],
    notes: '',
    versionAdded: 'v1.0.0',
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // INFLUENCER — Auth
  // ─────────────────────────────────────────────────────────────────────────────
  {
    id: 'I-AUTH-1',
    role: 'Influencer',
    module: 'Authentication',
    moduleCode: 'I-AUTH',
    story: 'View welcome/onboarding screen',
    status: 'DONE',
    routes: ['/auth/influencer/welcome'],
    apiEndpoints: [],
    components: ['AuthLayout', 'AuthCard', 'ProgressDots'],
    screenshotIds: ['SCR-I-AUTH-1'],
    notes: '',
    versionAdded: 'v1.0.0',
  },
  {
    id: 'I-AUTH-2',
    role: 'Influencer',
    module: 'Authentication',
    moduleCode: 'I-AUTH',
    story: 'Log in with email/password',
    status: 'DONE',
    routes: ['/auth/influencer/login'],
    apiEndpoints: ['Firebase Auth SDK'],
    components: [],
    screenshotIds: ['SCR-I-AUTH-2'],
    notes: '',
    versionAdded: 'v1.0.0',
  },
  {
    id: 'I-AUTH-3',
    role: 'Influencer',
    module: 'Authentication',
    moduleCode: 'I-AUTH',
    story: 'Log in with Google, Facebook, or Apple',
    status: 'DONE',
    routes: ['/auth/influencer/login'],
    apiEndpoints: ['Firebase Auth SDK (OAuth)'],
    components: [],
    screenshotIds: ['SCR-I-AUTH-3'],
    notes: '',
    versionAdded: 'v1.0.0',
  },
  {
    id: 'I-AUTH-4',
    role: 'Influencer',
    module: 'Authentication',
    moduleCode: 'I-AUTH',
    story: 'Sign up with email',
    status: 'DONE',
    routes: ['/auth/influencer/signup/email'],
    apiEndpoints: ['Firebase Auth SDK', 'Firestore'],
    components: [],
    screenshotIds: ['SCR-I-AUTH-4'],
    notes: '',
    versionAdded: 'v1.0.0',
  },
  {
    id: 'I-AUTH-5',
    role: 'Influencer',
    module: 'Authentication',
    moduleCode: 'I-AUTH',
    story: 'Verify email',
    status: 'DONE',
    routes: [
      '/auth/influencer/signup/verify-email',
      '/auth/influencer/signup/email-verified',
    ],
    apiEndpoints: ['POST /api/auth/resend-verification'],
    components: [],
    screenshotIds: ['SCR-I-AUTH-5'],
    notes: '',
    versionAdded: 'v1.0.0',
  },
  {
    id: 'I-AUTH-6',
    role: 'Influencer',
    module: 'Authentication',
    moduleCode: 'I-AUTH',
    story: 'Verify social media accounts',
    status: 'DONE',
    routes: [
      '/auth/influencer/verify/social',
      '/auth/influencer/verify/success',
    ],
    apiEndpoints: [],
    components: [],
    screenshotIds: ['SCR-I-AUTH-6'],
    notes: '',
    versionAdded: 'v1.0.0',
  },
  {
    id: 'I-AUTH-7',
    role: 'Influencer',
    module: 'Authentication',
    moduleCode: 'I-AUTH',
    story: 'Reset password',
    status: 'DONE',
    routes: [
      '/auth/influencer/forgot-password',
      '/auth/influencer/reset-password',
      '/auth/influencer/reset-success',
    ],
    apiEndpoints: ['Firebase Auth SDK'],
    components: [],
    screenshotIds: ['SCR-I-AUTH-7'],
    notes: '',
    versionAdded: 'v1.0.0',
  },
  {
    id: 'I-AUTH-8',
    role: 'Influencer',
    module: 'Authentication',
    moduleCode: 'I-AUTH',
    story: 'Must complete profile',
    status: 'DONE',
    routes: ['/auth/influencer/complete-profile'],
    apiEndpoints: ['Firestore'],
    components: [],
    screenshotIds: ['SCR-I-AUTH-8'],
    notes: '',
    versionAdded: 'v1.0.0',
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // INFLUENCER — Dashboard
  // ─────────────────────────────────────────────────────────────────────────────
  {
    id: 'I-DASH-1',
    role: 'Influencer',
    module: 'Dashboard',
    moduleCode: 'I-DASH',
    story: 'Welcome greeting with 4 stats',
    status: 'DONE',
    routes: ['/influencers'],
    apiEndpoints: ['GET /api/influencers/applications'],
    components: ['InfluencerStatsCard'],
    screenshotIds: ['SCR-I-DASH-1'],
    notes: '',
    versionAdded: 'v1.0.0',
  },
  {
    id: 'I-DASH-2',
    role: 'Influencer',
    module: 'Dashboard',
    moduleCode: 'I-DASH',
    story: 'See active campaigns (limit 3)',
    status: 'DONE',
    routes: ['/influencers'],
    apiEndpoints: ['GET /api/influencers/applications'],
    components: [],
    screenshotIds: ['SCR-I-DASH-2'],
    notes: '',
    versionAdded: 'v1.0.0',
  },
  {
    id: 'I-DASH-3',
    role: 'Influencer',
    module: 'Dashboard',
    moduleCode: 'I-DASH',
    story: 'See pending applications (limit 3)',
    status: 'DONE',
    routes: ['/influencers'],
    apiEndpoints: ['GET /api/influencers/applications'],
    components: [],
    screenshotIds: ['SCR-I-DASH-3'],
    notes: '',
    versionAdded: 'v1.0.0',
  },
  {
    id: 'I-DASH-4',
    role: 'Influencer',
    module: 'Dashboard',
    moduleCode: 'I-DASH',
    story: 'See recommended campaigns',
    status: 'DONE',
    routes: ['/influencers'],
    apiEndpoints: ['GET /api/influencers/campaigns/marketplace'],
    components: [],
    screenshotIds: ['SCR-I-DASH-4'],
    notes: '',
    versionAdded: 'v1.0.0',
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // INFLUENCER — Marketplace
  // ─────────────────────────────────────────────────────────────────────────────
  {
    id: 'I-MKTPL-1',
    role: 'Influencer',
    module: 'Marketplace',
    moduleCode: 'I-MKTPL',
    story: 'Browse campaigns in grid/list view',
    status: 'DONE',
    routes: ['/influencers/marketplace'],
    apiEndpoints: ['GET /api/influencers/campaigns/marketplace'],
    components: ['MarketplaceCampaignCard'],
    screenshotIds: ['SCR-I-MKTPL-1'],
    notes: '',
    versionAdded: 'v1.0.0',
  },
  {
    id: 'I-MKTPL-2',
    role: 'Influencer',
    module: 'Marketplace',
    moduleCode: 'I-MKTPL',
    story: 'Filter by platform, category, budget',
    status: 'DONE',
    routes: ['/influencers/marketplace'],
    apiEndpoints: ['GET /api/influencers/campaigns/marketplace'],
    components: ['CampaignFilterSidebar'],
    screenshotIds: ['SCR-I-MKTPL-2'],
    notes: '',
    versionAdded: 'v1.0.0',
  },
  {
    id: 'I-MKTPL-3',
    role: 'Influencer',
    module: 'Marketplace',
    moduleCode: 'I-MKTPL',
    story: 'Search and sort campaigns',
    status: 'DONE',
    routes: ['/influencers/marketplace', '/influencers/marketplace/search'],
    apiEndpoints: ['GET /api/influencers/campaigns/marketplace'],
    components: [],
    screenshotIds: ['SCR-I-MKTPL-3'],
    notes: '',
    versionAdded: 'v1.0.0',
  },
  {
    id: 'I-MKTPL-4',
    role: 'Influencer',
    module: 'Marketplace',
    moduleCode: 'I-MKTPL',
    story: 'Save campaigns to view later',
    status: 'DONE',
    routes: ['/influencers/marketplace'],
    apiEndpoints: ['POST /api/influencers/campaigns/saved'],
    components: [],
    screenshotIds: ['SCR-I-MKTPL-4'],
    notes: '',
    versionAdded: 'v1.0.0',
  },
  {
    id: 'I-MKTPL-5',
    role: 'Influencer',
    module: 'Marketplace',
    moduleCode: 'I-MKTPL',
    story: 'View full campaign brief',
    status: 'DONE',
    routes: ['/influencers/marketplace/[id]'],
    apiEndpoints: ['GET /api/influencers/campaigns/[id]'],
    components: [],
    screenshotIds: ['SCR-I-MKTPL-5'],
    notes: '',
    versionAdded: 'v1.0.0',
  },
  {
    id: 'I-MKTPL-6',
    role: 'Influencer',
    module: 'Marketplace',
    moduleCode: 'I-MKTPL',
    story: 'Apply with pitch, rate, screening answers',
    status: 'DONE',
    routes: ['/influencers/marketplace/[id]'],
    apiEndpoints: ['POST /api/influencers/campaigns/[id]/apply'],
    components: ['ApplicationModal'],
    screenshotIds: ['SCR-I-MKTPL-6'],
    notes: '',
    versionAdded: 'v1.0.0',
  },
  {
    id: 'I-MKTPL-7',
    role: 'Influencer',
    module: 'Marketplace',
    moduleCode: 'I-MKTPL',
    story: 'See success confirmation after applying',
    status: 'DONE',
    routes: ['/influencers/marketplace/[id]'],
    apiEndpoints: [],
    components: [],
    screenshotIds: ['SCR-I-MKTPL-7'],
    notes: '',
    versionAdded: 'v1.0.0',
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // INFLUENCER — My Campaigns
  // ─────────────────────────────────────────────────────────────────────────────
  {
    id: 'I-CAMP-1',
    role: 'Influencer',
    module: 'My Campaigns',
    moduleCode: 'I-CAMP',
    story: 'View campaigns by tabs (Active, Applications, Saved, Completed)',
    status: 'DONE',
    routes: ['/influencers/campaigns'],
    apiEndpoints: ['GET /api/influencers/applications'],
    components: [
      'ActiveCampaignsTab',
      'ApplicationsTableTab',
      'SavedCampaignsTab',
      'CompletedCampaignsTab',
    ],
    screenshotIds: ['SCR-I-CAMP-1'],
    notes: '',
    versionAdded: 'v1.0.0',
  },
  {
    id: 'I-CAMP-2',
    role: 'Influencer',
    module: 'My Campaigns',
    moduleCode: 'I-CAMP',
    story: 'View campaign details with 5 tabs',
    status: 'DONE',
    routes: ['/influencers/campaigns/[id]'],
    apiEndpoints: ['GET /api/influencers/campaigns/[id]'],
    components: [
      'CampaignOverviewTab',
      'CampaignContentTab',
      'CampaignBriefTab',
      'CampaignPaymentsTab',
      'CampaignAnalyticsTab',
    ],
    screenshotIds: [
      'SCR-I-CAMP-2-OVERVIEW',
      'SCR-I-CAMP-2-CONTENT',
      'SCR-I-CAMP-2-BRIEF',
      'SCR-I-CAMP-2-PAYMENTS',
      'SCR-I-CAMP-2-ANALYTICS',
    ],
    notes: '',
    versionAdded: 'v1.0.0',
  },
  {
    id: 'I-CAMP-3',
    role: 'Influencer',
    module: 'My Campaigns',
    moduleCode: 'I-CAMP',
    story: 'Submit content for deliverable',
    status: 'DONE',
    routes: ['/influencers/campaigns/[id]/submit-content'],
    apiEndpoints: ['POST /api/influencers/campaigns/[id]/submit-content'],
    components: [],
    screenshotIds: ['SCR-I-CAMP-3'],
    notes: '',
    versionAdded: 'v1.0.0',
  },
  {
    id: 'I-CAMP-4',
    role: 'Influencer',
    module: 'My Campaigns',
    moduleCode: 'I-CAMP',
    story: 'Search and filter within campaigns',
    status: 'DONE',
    routes: ['/influencers/campaigns'],
    apiEndpoints: [],
    components: [],
    screenshotIds: ['SCR-I-CAMP-4'],
    notes: '',
    versionAdded: 'v1.0.0',
  },
  {
    id: 'I-CAMP-5',
    role: 'Influencer',
    module: 'My Campaigns',
    moduleCode: 'I-CAMP',
    story: 'View saved campaigns',
    status: 'DONE',
    routes: ['/influencers/campaigns'],
    apiEndpoints: ['GET /api/influencers/campaigns/saved'],
    components: [],
    screenshotIds: ['SCR-I-CAMP-5'],
    notes: '',
    versionAdded: 'v1.0.0',
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // INFLUENCER — Applications
  // ─────────────────────────────────────────────────────────────────────────────
  {
    id: 'I-APP-1',
    role: 'Influencer',
    module: 'Applications',
    moduleCode: 'I-APP',
    story: 'See application stats',
    status: 'DONE',
    routes: ['/influencers/campaign-applications'],
    apiEndpoints: ['GET /api/influencers/applications'],
    components: ['CampaignApplicationCard'],
    screenshotIds: ['SCR-I-APP-1'],
    notes: '',
    versionAdded: 'v1.0.0',
  },
  {
    id: 'I-APP-2',
    role: 'Influencer',
    module: 'Applications',
    moduleCode: 'I-APP',
    story: 'Search and filter applications by status',
    status: 'DONE',
    routes: ['/influencers/campaign-applications'],
    apiEndpoints: ['GET /api/influencers/applications'],
    components: [],
    screenshotIds: ['SCR-I-APP-2'],
    notes: '',
    versionAdded: 'v1.0.0',
  },
  {
    id: 'I-APP-3',
    role: 'Influencer',
    module: 'Applications',
    moduleCode: 'I-APP',
    story: 'Sort applications',
    status: 'DONE',
    routes: ['/influencers/campaign-applications'],
    apiEndpoints: [],
    components: [],
    screenshotIds: ['SCR-I-APP-3'],
    notes: '',
    versionAdded: 'v1.0.0',
  },
  {
    id: 'I-APP-4',
    role: 'Influencer',
    module: 'Applications',
    moduleCode: 'I-APP',
    story: 'Withdraw pending application',
    status: 'DONE',
    routes: ['/influencers/campaign-applications'],
    apiEndpoints: ['DELETE /api/influencers/applications/[id]'],
    components: ['WithdrawalModal'],
    screenshotIds: ['SCR-I-APP-4'],
    notes: '',
    versionAdded: 'v1.0.0',
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // INFLUENCER — Invitations
  // ─────────────────────────────────────────────────────────────────────────────
  {
    id: 'I-INV-1',
    role: 'Influencer',
    module: 'Invitations',
    moduleCode: 'I-INV',
    story: 'View campaign invitations from brands',
    status: 'DONE',
    routes: ['/influencers/invitations'],
    apiEndpoints: ['GET /api/influencers/invitations'],
    components: [],
    screenshotIds: ['SCR-I-INV-1'],
    notes: '',
    versionAdded: 'v1.0.0',
  },
  {
    id: 'I-INV-2',
    role: 'Influencer',
    module: 'Invitations',
    moduleCode: 'I-INV',
    story: 'Accept or decline invitation',
    status: 'DONE',
    routes: ['/influencers/invitations'],
    apiEndpoints: ['PATCH /api/influencers/invitations/[id]'],
    components: [],
    screenshotIds: ['SCR-I-INV-2'],
    notes: '',
    versionAdded: 'v1.0.0',
  },
  {
    id: 'I-INV-3',
    role: 'Influencer',
    module: 'Invitations',
    moduleCode: 'I-INV',
    story: 'Preview campaign details from invitation',
    status: 'DONE',
    routes: ['/influencers/invitations'],
    apiEndpoints: [],
    components: [],
    screenshotIds: ['SCR-I-INV-3'],
    notes: '',
    versionAdded: 'v1.0.0',
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // INFLUENCER — Notifications
  // ─────────────────────────────────────────────────────────────────────────────
  {
    id: 'I-NOTIF-1',
    role: 'Influencer',
    module: 'Notifications',
    moduleCode: 'I-NOTIF',
    story: 'View all notifications with type-specific icons',
    status: 'DONE',
    routes: ['/influencers/notifications'],
    apiEndpoints: ['GET /api/notifications'],
    components: [],
    screenshotIds: ['SCR-I-NOTIF-1'],
    notes: '',
    versionAdded: 'v1.0.0',
  },
  {
    id: 'I-NOTIF-2',
    role: 'Influencer',
    module: 'Notifications',
    moduleCode: 'I-NOTIF',
    story: 'Filter All/Unread',
    status: 'DONE',
    routes: ['/influencers/notifications'],
    apiEndpoints: ['GET /api/notifications'],
    components: [],
    screenshotIds: ['SCR-I-NOTIF-2'],
    notes: '',
    versionAdded: 'v1.0.0',
  },
  {
    id: 'I-NOTIF-3',
    role: 'Influencer',
    module: 'Notifications',
    moduleCode: 'I-NOTIF',
    story: 'Mark individual as read',
    status: 'DONE',
    routes: ['/influencers/notifications'],
    apiEndpoints: ['PATCH /api/notifications/{id}'],
    components: [],
    screenshotIds: ['SCR-I-NOTIF-3'],
    notes: '',
    versionAdded: 'v1.0.0',
  },
  {
    id: 'I-NOTIF-4',
    role: 'Influencer',
    module: 'Notifications',
    moduleCode: 'I-NOTIF',
    story: 'Bulk mark all as read',
    status: 'DONE',
    routes: ['/influencers/notifications'],
    apiEndpoints: ['POST /api/notifications/mark-all-read'],
    components: [],
    screenshotIds: ['SCR-I-NOTIF-4'],
    notes: '',
    versionAdded: 'v1.0.0',
  },
  {
    id: 'I-NOTIF-5',
    role: 'Influencer',
    module: 'Notifications',
    moduleCode: 'I-NOTIF',
    story: 'Click notification to navigate to relevant page',
    status: 'DONE',
    routes: ['/influencers/notifications'],
    apiEndpoints: [],
    components: [],
    screenshotIds: ['SCR-I-NOTIF-5'],
    notes: '',
    versionAdded: 'v1.0.0',
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // INFLUENCER — Profile
  // ─────────────────────────────────────────────────────────────────────────────
  {
    id: 'I-PROF-1',
    role: 'Influencer',
    module: 'Profile',
    moduleCode: 'I-PROF',
    story: 'View profile overview with enriched data',
    status: 'DONE',
    routes: ['/influencers/profile'],
    apiEndpoints: [
      'GET /api/influencer/my-profile',
      'GET /api/influencer/profiles/[id]/enrichment',
    ],
    components: [
      'CreatorProfileCard',
      'ProfileSnapshot',
      'InsightsCard',
      'MetricsTable',
      'ContentGrid',
      'DemographicsSection',
      'SimilarCreators',
    ],
    screenshotIds: ['SCR-I-PROF-1'],
    notes: '',
    versionAdded: 'v1.0.0',
  },
  {
    id: 'I-PROF-2',
    role: 'Influencer',
    module: 'Profile',
    moduleCode: 'I-PROF',
    story: 'Edit profile settings',
    status: 'DONE',
    routes: ['/influencers/profile'],
    apiEndpoints: [
      'POST /api/influencer/my-profile',
      'POST /api/influencer/my-profile/link-account',
    ],
    components: ['SettingsTab'],
    screenshotIds: ['SCR-I-PROF-2'],
    notes: '',
    versionAdded: 'v1.0.0',
  },
  {
    id: 'I-PROF-3',
    role: 'Influencer',
    module: 'Profile',
    moduleCode: 'I-PROF',
    story: 'Stale profile data auto-refreshed',
    status: 'DONE',
    routes: ['/influencers/profile'],
    apiEndpoints: [
      'GET /api/influencer/{id}/enrichment',
      'POST /api/influencer/{id}/enrichment',
    ],
    components: ['EnrichmentBanner'],
    screenshotIds: ['SCR-I-PROF-3'],
    notes: '',
    versionAdded: 'v1.0.0',
  },
  {
    id: 'I-PROF-4',
    role: 'Influencer',
    module: 'Profile',
    moduleCode: 'I-PROF',
    story: 'See clickable links to original posts',
    status: 'DONE',
    routes: ['/influencers/profile'],
    apiEndpoints: ['GET /api/influencer/{id}/enrichment'],
    components: ['ContentGrid'],
    screenshotIds: ['SCR-I-PROF-4'],
    notes: '',
    versionAdded: 'v1.0.0',
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // INFLUENCER — Calendar
  // ─────────────────────────────────────────────────────────────────────────────
  {
    id: 'I-CAL-1',
    role: 'Influencer',
    module: 'Calendar',
    moduleCode: 'I-CAL',
    story: 'View calendar with month/week/day views',
    status: 'PARTIAL',
    routes: ['/influencers/calendar'],
    apiEndpoints: [],
    components: [],
    screenshotIds: ['SCR-I-CAL-1'],
    notes: 'Full calendar UI implemented, no API integration',
    versionAdded: 'v1.0.0',
  },
  {
    id: 'I-CAL-2',
    role: 'Influencer',
    module: 'Calendar',
    moduleCode: 'I-CAL',
    story: 'See upcoming events in sidebar',
    status: 'PARTIAL',
    routes: ['/influencers/calendar'],
    apiEndpoints: [],
    components: [],
    screenshotIds: ['SCR-I-CAL-2'],
    notes: 'Mock data only',
    versionAdded: 'v1.0.0',
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // INFLUENCER — Content
  // ─────────────────────────────────────────────────────────────────────────────
  {
    id: 'I-CONT-1',
    role: 'Influencer',
    module: 'Content',
    moduleCode: 'I-CONT',
    story: 'Select deliverable type and platform',
    status: 'DONE',
    routes: ['/influencers/campaigns/[id]/submit-content'],
    apiEndpoints: ['POST /api/influencers/campaigns/[id]/submit-content'],
    components: [],
    screenshotIds: ['SCR-I-CONT-1'],
    notes: '',
    versionAdded: 'v1.0.0',
  },
  {
    id: 'I-CONT-2',
    role: 'Influencer',
    module: 'Content',
    moduleCode: 'I-CONT',
    story: 'Provide content URL, caption, hashtags',
    status: 'DONE',
    routes: ['/influencers/campaigns/[id]/submit-content'],
    apiEndpoints: ['POST /api/influencers/campaigns/[id]/submit-content'],
    components: [],
    screenshotIds: ['SCR-I-CONT-2'],
    notes: '',
    versionAdded: 'v1.0.0',
  },
  {
    id: 'I-CONT-3',
    role: 'Influencer',
    module: 'Content',
    moduleCode: 'I-CONT',
    story: 'Upload screenshot of posted content',
    status: 'DONE',
    routes: ['/influencers/campaigns/[id]/submit-content'],
    apiEndpoints: ['Firebase Storage'],
    components: [],
    screenshotIds: ['SCR-I-CONT-3'],
    notes: '',
    versionAdded: 'v1.0.0',
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // SHARED — Utility
  // ─────────────────────────────────────────────────────────────────────────────
  {
    id: 'S-UTIL-1',
    role: 'Shared',
    module: 'Utility',
    moduleCode: 'S-UTIL',
    story: 'Role selection page',
    status: 'DONE',
    routes: ['/'],
    apiEndpoints: [],
    components: ['RoleCard'],
    screenshotIds: ['SCR-S-UTIL-1'],
    notes: '',
    versionAdded: 'v1.0.0',
  },
  {
    id: 'S-UTIL-2',
    role: 'Shared',
    module: 'Utility',
    moduleCode: 'S-UTIL',
    story: 'Terms of Service',
    status: 'DONE',
    routes: ['/terms'],
    apiEndpoints: [],
    components: [],
    screenshotIds: ['SCR-S-UTIL-2'],
    notes: '',
    versionAdded: 'v1.0.0',
  },
  {
    id: 'S-UTIL-3',
    role: 'Shared',
    module: 'Utility',
    moduleCode: 'S-UTIL',
    story: 'Privacy Policy',
    status: 'DONE',
    routes: ['/privacy'],
    apiEndpoints: [],
    components: [],
    screenshotIds: ['SCR-S-UTIL-3'],
    notes: '',
    versionAdded: 'v1.0.0',
  },
  {
    id: 'S-UTIL-4',
    role: 'Shared',
    module: 'Utility',
    moduleCode: 'S-UTIL',
    story: 'Data deletion request',
    status: 'DONE',
    routes: ['/data-deletion'],
    apiEndpoints: [],
    components: [],
    screenshotIds: ['SCR-S-UTIL-4'],
    notes: '',
    versionAdded: 'v1.0.0',
  },
  {
    id: 'S-UTIL-5',
    role: 'Shared',
    module: 'Utility',
    moduleCode: 'S-UTIL',
    story: 'Unauthorized page',
    status: 'DONE',
    routes: ['/unauthorized'],
    apiEndpoints: [],
    components: [],
    screenshotIds: ['SCR-S-UTIL-5'],
    notes: '',
    versionAdded: 'v1.0.0',
  },
  {
    id: 'S-UTIL-6',
    role: 'Shared',
    module: 'Utility',
    moduleCode: 'S-UTIL',
    story: 'API documentation',
    status: 'DONE',
    routes: ['/api-docs'],
    apiEndpoints: [],
    components: ['Scalar'],
    screenshotIds: ['SCR-S-UTIL-6'],
    notes: '',
    versionAdded: 'v1.0.0',
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // PHASE 2: BRAND — Workspace Management
  // ─────────────────────────────────────────────────────────────────────────────
  {
    id: 'B-WORK-1',
    role: 'Brand',
    module: 'Workspace Management',
    moduleCode: 'B-WORK',
    story: 'Create a new workspace to organise brand campaigns and team',
    status: 'PLACEHOLDER',
    routes: ['/brands/workspace/create'],
    apiEndpoints: ['POST /api/workspaces'],
    components: ['WorkspaceCreateWizard'],
    screenshotIds: ['SCR-B-WORK-1'],
    notes: 'P0 — Launch blocker. Foundation for all Phase 2 features.',
    versionAdded: 'v2.0.0',
  },
  {
    id: 'B-WORK-2',
    role: 'Brand',
    module: 'Workspace Management',
    moduleCode: 'B-WORK',
    story: 'Name workspace and upload brand logo',
    status: 'PLACEHOLDER',
    routes: ['/brands/workspace/settings'],
    apiEndpoints: ['PATCH /api/workspaces/{id}'],
    components: ['WorkspaceSettings', 'LogoUploader'],
    screenshotIds: ['SCR-B-WORK-2'],
    notes: 'P0',
    versionAdded: 'v2.0.0',
  },
  {
    id: 'B-WORK-3',
    role: 'Brand',
    module: 'Workspace Management',
    moduleCode: 'B-WORK',
    story: 'Configure workspace settings (brand name, industry, website)',
    status: 'PLACEHOLDER',
    routes: ['/brands/workspace/settings'],
    apiEndpoints: ['PATCH /api/workspaces/{id}'],
    components: ['WorkspaceSettings'],
    screenshotIds: ['SCR-B-WORK-3'],
    notes: 'P0',
    versionAdded: 'v2.0.0',
  },
  {
    id: 'B-WORK-4',
    role: 'Brand',
    module: 'Workspace Management',
    moduleCode: 'B-WORK',
    story: 'Switch between workspaces via sidebar switcher',
    status: 'PLACEHOLDER',
    routes: ['/brands/dashboard'],
    apiEndpoints: ['GET /api/workspaces'],
    components: ['WorkspaceSwitcher', 'Sidebar'],
    screenshotIds: ['SCR-B-WORK-4'],
    notes: 'P0 — Figma-like workspace switcher in sidebar.',
    versionAdded: 'v2.0.0',
  },
  {
    id: 'B-WORK-5',
    role: 'Brand',
    module: 'Workspace Management',
    moduleCode: 'B-WORK',
    story: 'View workspace dashboard with usage stats (searches, campaigns, seats)',
    status: 'PLACEHOLDER',
    routes: ['/brands/workspace/dashboard'],
    apiEndpoints: ['GET /api/workspaces/{id}/usage'],
    components: ['WorkspaceDashboard', 'UsageCards'],
    screenshotIds: ['SCR-B-WORK-5'],
    notes: 'P0',
    versionAdded: 'v2.0.0',
  },
  {
    id: 'B-WORK-6',
    role: 'Brand',
    module: 'Workspace Management',
    moduleCode: 'B-WORK',
    story: 'Set workspace-level notification preferences',
    status: 'PLACEHOLDER',
    routes: ['/brands/workspace/settings'],
    apiEndpoints: ['PATCH /api/workspaces/{id}/notifications'],
    components: ['NotificationSettings'],
    screenshotIds: ['SCR-B-WORK-6'],
    notes: 'P1',
    versionAdded: 'v2.0.0',
  },
  {
    id: 'B-WORK-7',
    role: 'Brand',
    module: 'Workspace Management',
    moduleCode: 'B-WORK',
    story: 'Archive a workspace (soft delete) without losing data',
    status: 'PLACEHOLDER',
    routes: ['/brands/workspace/settings'],
    apiEndpoints: ['PATCH /api/workspaces/{id}/archive'],
    components: ['WorkspaceSettings', 'ConfirmDialog'],
    screenshotIds: ['SCR-B-WORK-7'],
    notes: 'P1',
    versionAdded: 'v2.0.0',
  },
  {
    id: 'B-WORK-8',
    role: 'Brand',
    module: 'Workspace Management',
    moduleCode: 'B-WORK',
    story: 'Permanently delete workspace after 30-day grace period',
    status: 'PLACEHOLDER',
    routes: ['/brands/workspace/settings'],
    apiEndpoints: ['DELETE /api/workspaces/{id}'],
    components: ['WorkspaceSettings', 'DeleteConfirmDialog'],
    screenshotIds: ['SCR-B-WORK-8'],
    notes: 'P2',
    versionAdded: 'v2.0.0',
  },
  {
    id: 'B-WORK-9',
    role: 'Brand',
    module: 'Workspace Management',
    moduleCode: 'B-WORK',
    story: 'Export all workspace data (campaigns, influencers, analytics) as CSV/JSON',
    status: 'PLACEHOLDER',
    routes: ['/brands/workspace/settings'],
    apiEndpoints: ['GET /api/workspaces/{id}/export'],
    components: ['ExportDataModal'],
    screenshotIds: ['SCR-B-WORK-9'],
    notes: 'P1 — Required for POPIA compliance.',
    versionAdded: 'v2.0.0',
  },
  {
    id: 'B-WORK-10',
    role: 'Brand',
    module: 'Workspace Management',
    moduleCode: 'B-WORK',
    story: 'All campaigns scoped to current workspace (data isolation)',
    status: 'PLACEHOLDER',
    routes: [],
    apiEndpoints: ['GET /api/campaigns'],
    components: [],
    screenshotIds: [],
    notes: 'P0 — Backend data scoping. No dedicated UI.',
    versionAdded: 'v2.0.0',
  },
  {
    id: 'B-WORK-11',
    role: 'Brand',
    module: 'Workspace Management',
    moduleCode: 'B-WORK',
    story: 'Search results and saved creators scoped to current workspace',
    status: 'PLACEHOLDER',
    routes: [],
    apiEndpoints: ['GET /api/search', 'GET /api/influencer/profiles'],
    components: [],
    screenshotIds: [],
    notes: 'P0 — Backend data scoping. No dedicated UI.',
    versionAdded: 'v2.0.0',
  },
  {
    id: 'B-WORK-12',
    role: 'Brand',
    module: 'Workspace Management',
    moduleCode: 'B-WORK',
    story: 'Visual indicator in sidebar/header showing current workspace',
    status: 'PLACEHOLDER',
    routes: ['/brands/dashboard'],
    apiEndpoints: [],
    components: ['Sidebar', 'WorkspaceIndicator'],
    screenshotIds: ['SCR-B-WORK-12'],
    notes: 'P0',
    versionAdded: 'v2.0.0',
  },
  {
    id: 'B-WORK-13',
    role: 'Brand',
    module: 'Workspace Management',
    moduleCode: 'B-WORK',
    story: 'Transfer workspace ownership to another member',
    status: 'PLACEHOLDER',
    routes: ['/brands/workspace/settings'],
    apiEndpoints: ['POST /api/workspaces/{id}/transfer'],
    components: ['TransferOwnershipModal'],
    screenshotIds: ['SCR-B-WORK-13'],
    notes: 'P2',
    versionAdded: 'v2.0.0',
  },
  {
    id: 'B-WORK-14',
    role: 'Brand',
    module: 'Workspace Management',
    moduleCode: 'B-WORK',
    story: 'Customize workspace default currency (ZAR, USD, EUR, GBP)',
    status: 'PLACEHOLDER',
    routes: ['/brands/workspace/settings'],
    apiEndpoints: ['PATCH /api/workspaces/{id}'],
    components: ['WorkspaceSettings'],
    screenshotIds: ['SCR-B-WORK-14'],
    notes: 'P1',
    versionAdded: 'v2.0.0',
  },
  {
    id: 'B-WORK-15',
    role: 'Brand',
    module: 'Workspace Management',
    moduleCode: 'B-WORK',
    story: 'Guided workspace creation wizard (name → brand details → select plan → invite team)',
    status: 'PLACEHOLDER',
    routes: ['/brands/workspace/create'],
    apiEndpoints: ['POST /api/workspaces'],
    components: ['WorkspaceCreateWizard', 'PlanSelector', 'TeamInviteStep'],
    screenshotIds: ['SCR-B-WORK-15-S1', 'SCR-B-WORK-15-S2', 'SCR-B-WORK-15-S3', 'SCR-B-WORK-15-S4'],
    notes: 'P0 — Multi-step onboarding wizard.',
    versionAdded: 'v2.0.0',
  },
  {
    id: 'B-WORK-16',
    role: 'Brand',
    module: 'Workspace Management',
    moduleCode: 'B-WORK',
    story: 'Workspace switcher shows plan tier and brand logo per workspace',
    status: 'PLACEHOLDER',
    routes: ['/brands/dashboard'],
    apiEndpoints: ['GET /api/workspaces'],
    components: ['WorkspaceSwitcher'],
    screenshotIds: ['SCR-B-WORK-16'],
    notes: 'P1',
    versionAdded: 'v2.0.0',
  },
  {
    id: 'B-WORK-17',
    role: 'Brand',
    module: 'Workspace Management',
    moduleCode: 'B-WORK',
    story: 'Workspace-level audit logs showing who did what and when',
    status: 'PLACEHOLDER',
    routes: ['/brands/workspace/audit-log'],
    apiEndpoints: ['GET /api/workspaces/{id}/audit-log'],
    components: ['AuditLogTable'],
    screenshotIds: ['SCR-B-WORK-17'],
    notes: 'P2',
    versionAdded: 'v2.0.0',
  },
  {
    id: 'B-WORK-18',
    role: 'Brand',
    module: 'Workspace Management',
    moduleCode: 'B-WORK',
    story: 'Set workspace-wide brand colour/theme',
    status: 'PLACEHOLDER',
    routes: ['/brands/workspace/settings'],
    apiEndpoints: ['PATCH /api/workspaces/{id}'],
    components: ['ThemeCustomizer'],
    screenshotIds: ['SCR-B-WORK-18'],
    notes: 'P2',
    versionAdded: 'v2.0.0',
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // PHASE 2: BRAND — Subscription & Billing
  // ─────────────────────────────────────────────────────────────────────────────
  {
    id: 'B-SUB-1',
    role: 'Brand',
    module: 'Subscription & Billing',
    moduleCode: 'B-SUB',
    story: 'Select subscription plan (Discovery / Growth / Scale) during workspace creation',
    status: 'PLACEHOLDER',
    routes: ['/brands/workspace/create'],
    apiEndpoints: ['POST /api/subscriptions'],
    components: ['PlanSelector', 'PricingCards'],
    screenshotIds: ['SCR-B-SUB-1'],
    notes: 'P0 — Foundation for all billing.',
    versionAdded: 'v2.0.0',
  },
  {
    id: 'B-SUB-2',
    role: 'Brand',
    module: 'Subscription & Billing',
    moduleCode: 'B-SUB',
    story: 'Pay for subscription with credit card (Visa/Mastercard) via Stripe',
    status: 'PLACEHOLDER',
    routes: ['/brands/workspace/billing'],
    apiEndpoints: ['POST /api/subscriptions/checkout', 'POST /api/webhooks/stripe'],
    components: ['StripeCheckout', 'PaymentForm'],
    screenshotIds: ['SCR-B-SUB-2'],
    notes: 'P0 — Stripe integration (XL).',
    versionAdded: 'v2.0.0',
  },
  {
    id: 'B-SUB-3',
    role: 'Brand',
    module: 'Subscription & Billing',
    moduleCode: 'B-SUB',
    story: 'Pay via EFT (bank transfer) with proof of payment upload',
    status: 'PLACEHOLDER',
    routes: ['/brands/workspace/billing'],
    apiEndpoints: ['POST /api/subscriptions/eft'],
    components: ['EFTPaymentForm', 'FileUploader'],
    screenshotIds: ['SCR-B-SUB-3'],
    notes: 'P0 — South African banking support.',
    versionAdded: 'v2.0.0',
  },
  {
    id: 'B-SUB-4',
    role: 'Brand',
    module: 'Subscription & Billing',
    moduleCode: 'B-SUB',
    story: 'View current plan details (tier, price, renewal date, usage) on billing page',
    status: 'PLACEHOLDER',
    routes: ['/brands/workspace/billing'],
    apiEndpoints: ['GET /api/subscriptions/{id}'],
    components: ['BillingDashboard', 'PlanDetailsCard'],
    screenshotIds: ['SCR-B-SUB-4'],
    notes: 'P0',
    versionAdded: 'v2.0.0',
  },
  {
    id: 'B-SUB-5',
    role: 'Brand',
    module: 'Subscription & Billing',
    moduleCode: 'B-SUB',
    story: 'Upgrade plan with immediate effect and prorated billing',
    status: 'PLACEHOLDER',
    routes: ['/brands/workspace/billing'],
    apiEndpoints: ['POST /api/subscriptions/{id}/upgrade'],
    components: ['UpgradePlanModal', 'PricingCards'],
    screenshotIds: ['SCR-B-SUB-5'],
    notes: 'P0',
    versionAdded: 'v2.0.0',
  },
  {
    id: 'B-SUB-6',
    role: 'Brand',
    module: 'Subscription & Billing',
    moduleCode: 'B-SUB',
    story: 'Downgrade plan at end of current billing cycle',
    status: 'PLACEHOLDER',
    routes: ['/brands/workspace/billing'],
    apiEndpoints: ['POST /api/subscriptions/{id}/downgrade'],
    components: ['DowngradePlanModal'],
    screenshotIds: ['SCR-B-SUB-6'],
    notes: 'P1',
    versionAdded: 'v2.0.0',
  },
  {
    id: 'B-SUB-7',
    role: 'Brand',
    module: 'Subscription & Billing',
    moduleCode: 'B-SUB',
    story: 'Cancel subscription with explanation of consequences (data retained 90 days)',
    status: 'PLACEHOLDER',
    routes: ['/brands/workspace/billing'],
    apiEndpoints: ['POST /api/subscriptions/{id}/cancel'],
    components: ['CancelSubscriptionModal'],
    screenshotIds: ['SCR-B-SUB-7'],
    notes: 'P0',
    versionAdded: 'v2.0.0',
  },
  {
    id: 'B-SUB-8',
    role: 'Brand',
    module: 'Subscription & Billing',
    moduleCode: 'B-SUB',
    story: 'Download PDF invoices for each billing period',
    status: 'PLACEHOLDER',
    routes: ['/brands/workspace/billing'],
    apiEndpoints: ['GET /api/subscriptions/{id}/invoices'],
    components: ['InvoiceList', 'InvoiceDownloadButton'],
    screenshotIds: ['SCR-B-SUB-8'],
    notes: 'P0',
    versionAdded: 'v2.0.0',
  },
  {
    id: 'B-SUB-9',
    role: 'Brand',
    module: 'Subscription & Billing',
    moduleCode: 'B-SUB',
    story: 'Email notifications before renewal (7d), on payment success, and on payment failure',
    status: 'PLACEHOLDER',
    routes: [],
    apiEndpoints: ['POST /api/webhooks/stripe'],
    components: [],
    screenshotIds: [],
    notes: 'P0 — Backend email triggers, no dedicated UI.',
    versionAdded: 'v2.0.0',
  },
  {
    id: 'B-SUB-10',
    role: 'Brand',
    module: 'Subscription & Billing',
    moduleCode: 'B-SUB',
    story: 'Update payment method (swap credit card, switch between card and EFT)',
    status: 'PLACEHOLDER',
    routes: ['/brands/workspace/billing'],
    apiEndpoints: ['PATCH /api/subscriptions/{id}/payment-method'],
    components: ['PaymentMethodForm'],
    screenshotIds: ['SCR-B-SUB-10'],
    notes: 'P1',
    versionAdded: 'v2.0.0',
  },
  {
    id: 'B-SUB-11',
    role: 'Brand',
    module: 'Subscription & Billing',
    moduleCode: 'B-SUB',
    story: '3-day grace period on failed payments with retry before suspension',
    status: 'PLACEHOLDER',
    routes: [],
    apiEndpoints: ['POST /api/webhooks/stripe'],
    components: ['PaymentFailedBanner'],
    screenshotIds: ['SCR-B-SUB-11'],
    notes: 'P0 — Critical for preventing accidental churn.',
    versionAdded: 'v2.0.0',
  },
  {
    id: 'B-SUB-12',
    role: 'Brand',
    module: 'Subscription & Billing',
    moduleCode: 'B-SUB',
    story: 'Reactivate suspended subscription (pay outstanding balance → restore access)',
    status: 'PLACEHOLDER',
    routes: ['/brands/workspace/billing'],
    apiEndpoints: ['POST /api/subscriptions/{id}/reactivate'],
    components: ['ReactivateModal'],
    screenshotIds: ['SCR-B-SUB-12'],
    notes: 'P1',
    versionAdded: 'v2.0.0',
  },
  {
    id: 'B-SUB-13',
    role: 'Brand',
    module: 'Subscription & Billing',
    moduleCode: 'B-SUB',
    story: 'Stripe webhook handlers for payment events (succeeded, failed, updated, cancelled)',
    status: 'PLACEHOLDER',
    routes: [],
    apiEndpoints: ['POST /api/webhooks/stripe'],
    components: [],
    screenshotIds: [],
    notes: 'P0 — Backend only (XL). Critical for billing state sync.',
    versionAdded: 'v2.0.0',
  },
  {
    id: 'B-SUB-14',
    role: 'Brand',
    module: 'Subscription & Billing',
    moduleCode: 'B-SUB',
    story: 'EFT payment: see banking details and unique reference number',
    status: 'PLACEHOLDER',
    routes: ['/brands/workspace/billing'],
    apiEndpoints: ['GET /api/subscriptions/{id}/eft-details'],
    components: ['EFTDetailsCard'],
    screenshotIds: ['SCR-B-SUB-14'],
    notes: 'P0',
    versionAdded: 'v2.0.0',
  },
  {
    id: 'B-SUB-15',
    role: 'Brand',
    module: 'Subscription & Billing',
    moduleCode: 'B-SUB',
    story: 'Admin: manually approve/reject EFT proof of payment',
    status: 'PLACEHOLDER',
    routes: ['/admin/eft-approvals'],
    apiEndpoints: ['PATCH /api/admin/eft/{id}'],
    components: ['EFTApprovalQueue'],
    screenshotIds: ['SCR-B-SUB-15'],
    notes: 'P0 — Requires admin panel.',
    versionAdded: 'v2.0.0',
  },
  {
    id: 'B-SUB-16',
    role: 'Brand',
    module: 'Subscription & Billing',
    moduleCode: 'B-SUB',
    story: 'View billing history (all past payments, amounts, dates, statuses)',
    status: 'PLACEHOLDER',
    routes: ['/brands/workspace/billing'],
    apiEndpoints: ['GET /api/subscriptions/{id}/history'],
    components: ['BillingHistoryTable'],
    screenshotIds: ['SCR-B-SUB-16'],
    notes: 'P1',
    versionAdded: 'v2.0.0',
  },
  {
    id: 'B-SUB-17',
    role: 'Brand',
    module: 'Subscription & Billing',
    moduleCode: 'B-SUB',
    story: 'Add VAT number to billing profile for invoices',
    status: 'PLACEHOLDER',
    routes: ['/brands/workspace/billing'],
    apiEndpoints: ['PATCH /api/subscriptions/{id}'],
    components: ['BillingProfileForm'],
    screenshotIds: ['SCR-B-SUB-17'],
    notes: 'P1',
    versionAdded: 'v2.0.0',
  },
  {
    id: 'B-SUB-18',
    role: 'Brand',
    module: 'Subscription & Billing',
    moduleCode: 'B-SUB',
    story: 'Annual billing option (pay 10 months, get 12)',
    status: 'PLACEHOLDER',
    routes: ['/brands/workspace/billing'],
    apiEndpoints: ['POST /api/subscriptions/{id}/switch-annual'],
    components: ['AnnualToggle'],
    screenshotIds: ['SCR-B-SUB-18'],
    notes: 'P2',
    versionAdded: 'v2.0.0',
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // PHASE 2: BRAND — Team & Seat Management
  // ─────────────────────────────────────────────────────────────────────────────
  {
    id: 'B-TEAM-1',
    role: 'Brand',
    module: 'Team & Seat Management',
    moduleCode: 'B-TEAM',
    story: 'Define workspace role levels (Owner, Admin, Editor, Viewer) with permissions',
    status: 'PLACEHOLDER',
    routes: [],
    apiEndpoints: [],
    components: [],
    screenshotIds: [],
    notes: 'P0 — Data model / type definitions. No dedicated UI.',
    versionAdded: 'v2.0.0',
  },
  {
    id: 'B-TEAM-2',
    role: 'Brand',
    module: 'Team & Seat Management',
    moduleCode: 'B-TEAM',
    story: 'Invite team members via email to workspace',
    status: 'PLACEHOLDER',
    routes: ['/brands/workspace/team'],
    apiEndpoints: ['POST /api/workspaces/{id}/invitations'],
    components: ['InviteMemberModal'],
    screenshotIds: ['SCR-B-TEAM-2'],
    notes: 'P0',
    versionAdded: 'v2.0.0',
  },
  {
    id: 'B-TEAM-3',
    role: 'Brand',
    module: 'Team & Seat Management',
    moduleCode: 'B-TEAM',
    story: 'Accept invitation via email link → signup/login → auto-join workspace',
    status: 'PLACEHOLDER',
    routes: ['/auth/invite/accept'],
    apiEndpoints: ['POST /api/invitations/{token}/accept'],
    components: ['InviteAcceptPage'],
    screenshotIds: ['SCR-B-TEAM-3'],
    notes: 'P0',
    versionAdded: 'v2.0.0',
  },
  {
    id: 'B-TEAM-4',
    role: 'Brand',
    module: 'Team & Seat Management',
    moduleCode: 'B-TEAM',
    story: 'View team members list (name, email, role, status, last active)',
    status: 'PLACEHOLDER',
    routes: ['/brands/workspace/team'],
    apiEndpoints: ['GET /api/workspaces/{id}/members'],
    components: ['TeamMembersTable'],
    screenshotIds: ['SCR-B-TEAM-4'],
    notes: 'P0',
    versionAdded: 'v2.0.0',
  },
  {
    id: 'B-TEAM-5',
    role: 'Brand',
    module: 'Team & Seat Management',
    moduleCode: 'B-TEAM',
    story: 'Change a team member role (promote/demote)',
    status: 'PLACEHOLDER',
    routes: ['/brands/workspace/team'],
    apiEndpoints: ['PATCH /api/workspaces/{id}/members/{memberId}'],
    components: ['ChangeRoleDropdown'],
    screenshotIds: ['SCR-B-TEAM-5'],
    notes: 'P0',
    versionAdded: 'v2.0.0',
  },
  {
    id: 'B-TEAM-6',
    role: 'Brand',
    module: 'Team & Seat Management',
    moduleCode: 'B-TEAM',
    story: 'Deactivate a team member (revoke access without deleting)',
    status: 'PLACEHOLDER',
    routes: ['/brands/workspace/team'],
    apiEndpoints: ['PATCH /api/workspaces/{id}/members/{memberId}/deactivate'],
    components: ['TeamMembersTable', 'ConfirmDialog'],
    screenshotIds: ['SCR-B-TEAM-6'],
    notes: 'P0',
    versionAdded: 'v2.0.0',
  },
  {
    id: 'B-TEAM-7',
    role: 'Brand',
    module: 'Team & Seat Management',
    moduleCode: 'B-TEAM',
    story: 'Reactivate a previously deactivated member',
    status: 'PLACEHOLDER',
    routes: ['/brands/workspace/team'],
    apiEndpoints: ['PATCH /api/workspaces/{id}/members/{memberId}/reactivate'],
    components: ['TeamMembersTable'],
    screenshotIds: ['SCR-B-TEAM-7'],
    notes: 'P1',
    versionAdded: 'v2.0.0',
  },
  {
    id: 'B-TEAM-8',
    role: 'Brand',
    module: 'Team & Seat Management',
    moduleCode: 'B-TEAM',
    story: 'See seats used vs available (e.g., 2/3 seats)',
    status: 'PLACEHOLDER',
    routes: ['/brands/workspace/team'],
    apiEndpoints: ['GET /api/workspaces/{id}/members'],
    components: ['SeatCounter'],
    screenshotIds: ['SCR-B-TEAM-8'],
    notes: 'P0',
    versionAdded: 'v2.0.0',
  },
  {
    id: 'B-TEAM-9',
    role: 'Brand',
    module: 'Team & Seat Management',
    moduleCode: 'B-TEAM',
    story: 'Blocked from inviting beyond seat limit with upgrade prompt',
    status: 'PLACEHOLDER',
    routes: ['/brands/workspace/team'],
    apiEndpoints: ['POST /api/workspaces/{id}/invitations'],
    components: ['InviteMemberModal', 'UpgradePrompt'],
    screenshotIds: ['SCR-B-TEAM-9'],
    notes: 'P0',
    versionAdded: 'v2.0.0',
  },
  {
    id: 'B-TEAM-10',
    role: 'Brand',
    module: 'Team & Seat Management',
    moduleCode: 'B-TEAM',
    story: 'Purchase additional seats (add-ons) beyond plan included seats',
    status: 'PLACEHOLDER',
    routes: ['/brands/workspace/billing'],
    apiEndpoints: ['POST /api/subscriptions/{id}/add-seats'],
    components: ['AddSeatsModal'],
    screenshotIds: ['SCR-B-TEAM-10'],
    notes: 'P1',
    versionAdded: 'v2.0.0',
  },
  {
    id: 'B-TEAM-11',
    role: 'Brand',
    module: 'Team & Seat Management',
    moduleCode: 'B-TEAM',
    story: 'See only workspaces I belong to in workspace switcher',
    status: 'PLACEHOLDER',
    routes: ['/brands/dashboard'],
    apiEndpoints: ['GET /api/workspaces'],
    components: ['WorkspaceSwitcher'],
    screenshotIds: ['SCR-B-TEAM-11'],
    notes: 'P0',
    versionAdded: 'v2.0.0',
  },
  {
    id: 'B-TEAM-12',
    role: 'Brand',
    module: 'Team & Seat Management',
    moduleCode: 'B-TEAM',
    story: 'Resend pending workspace invitations',
    status: 'PLACEHOLDER',
    routes: ['/brands/workspace/team'],
    apiEndpoints: ['POST /api/workspaces/{id}/invitations/{invId}/resend'],
    components: ['TeamMembersTable'],
    screenshotIds: ['SCR-B-TEAM-12'],
    notes: 'P1',
    versionAdded: 'v2.0.0',
  },
  {
    id: 'B-TEAM-13',
    role: 'Brand',
    module: 'Team & Seat Management',
    moduleCode: 'B-TEAM',
    story: 'Revoke pending workspace invitations',
    status: 'PLACEHOLDER',
    routes: ['/brands/workspace/team'],
    apiEndpoints: ['DELETE /api/workspaces/{id}/invitations/{invId}'],
    components: ['TeamMembersTable'],
    screenshotIds: ['SCR-B-TEAM-13'],
    notes: 'P1',
    versionAdded: 'v2.0.0',
  },
  {
    id: 'B-TEAM-14',
    role: 'Brand',
    module: 'Team & Seat Management',
    moduleCode: 'B-TEAM',
    story: 'Leave a workspace voluntarily',
    status: 'PLACEHOLDER',
    routes: ['/brands/workspace/settings'],
    apiEndpoints: ['POST /api/workspaces/{id}/leave'],
    components: ['LeaveWorkspaceButton', 'ConfirmDialog'],
    screenshotIds: ['SCR-B-TEAM-14'],
    notes: 'P1',
    versionAdded: 'v2.0.0',
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // PHASE 2: BRAND — Usage Tracking & Limits
  // ─────────────────────────────────────────────────────────────────────────────
  {
    id: 'B-USAGE-1',
    role: 'Brand',
    module: 'Usage Tracking & Limits',
    moduleCode: 'B-USAGE',
    story: 'Usage dashboard showing searches (15/20), campaigns (3/5), seats (1/1)',
    status: 'PLACEHOLDER',
    routes: ['/brands/workspace/usage'],
    apiEndpoints: ['GET /api/workspaces/{id}/usage'],
    components: ['UsageDashboard', 'UsageProgressBar'],
    screenshotIds: ['SCR-B-USAGE-1'],
    notes: 'P0',
    versionAdded: 'v2.0.0',
  },
  {
    id: 'B-USAGE-2',
    role: 'Brand',
    module: 'Usage Tracking & Limits',
    moduleCode: 'B-USAGE',
    story: 'Warning at 80% of any usage limit (toast + banner)',
    status: 'PLACEHOLDER',
    routes: [],
    apiEndpoints: [],
    components: ['UsageWarningBanner', 'UsageWarningToast'],
    screenshotIds: ['SCR-B-USAGE-2'],
    notes: 'P0',
    versionAdded: 'v2.0.0',
  },
  {
    id: 'B-USAGE-3',
    role: 'Brand',
    module: 'Usage Tracking & Limits',
    moduleCode: 'B-USAGE',
    story: 'Blocked from actions at limit with upgrade prompt',
    status: 'PLACEHOLDER',
    routes: [],
    apiEndpoints: [],
    components: ['UsageLimitModal', 'UpgradePrompt'],
    screenshotIds: ['SCR-B-USAGE-3'],
    notes: 'P0',
    versionAdded: 'v2.0.0',
  },
  {
    id: 'B-USAGE-4',
    role: 'Brand',
    module: 'Usage Tracking & Limits',
    moduleCode: 'B-USAGE',
    story: 'Usage limits reset on billing cycle date (not calendar month)',
    status: 'PLACEHOLDER',
    routes: [],
    apiEndpoints: [],
    components: [],
    screenshotIds: [],
    notes: 'P0 — Backend logic, no dedicated UI.',
    versionAdded: 'v2.0.0',
  },
  {
    id: 'B-USAGE-5',
    role: 'Brand',
    module: 'Usage Tracking & Limits',
    moduleCode: 'B-USAGE',
    story: 'Usage history chart (searches/campaigns over time)',
    status: 'PLACEHOLDER',
    routes: ['/brands/workspace/usage'],
    apiEndpoints: ['GET /api/workspaces/{id}/usage/history'],
    components: ['UsageHistoryChart'],
    screenshotIds: ['SCR-B-USAGE-5'],
    notes: 'P1',
    versionAdded: 'v2.0.0',
  },
  {
    id: 'B-USAGE-6',
    role: 'Brand',
    module: 'Usage Tracking & Limits',
    moduleCode: 'B-USAGE',
    story: 'Per-member usage breakdown (who used how many searches)',
    status: 'PLACEHOLDER',
    routes: ['/brands/workspace/usage'],
    apiEndpoints: ['GET /api/workspaces/{id}/usage/members'],
    components: ['MemberUsageTable'],
    screenshotIds: ['SCR-B-USAGE-6'],
    notes: 'P2',
    versionAdded: 'v2.0.0',
  },
  {
    id: 'B-USAGE-7',
    role: 'Brand',
    module: 'Usage Tracking & Limits',
    moduleCode: 'B-USAGE',
    story: 'Search count decrements only on new unique searches',
    status: 'PLACEHOLDER',
    routes: [],
    apiEndpoints: [],
    components: [],
    screenshotIds: [],
    notes: 'P1 — Backend dedup logic.',
    versionAdded: 'v2.0.0',
  },
  {
    id: 'B-USAGE-8',
    role: 'Brand',
    module: 'Usage Tracking & Limits',
    moduleCode: 'B-USAGE',
    story: 'Scale tier: unlimited searches and campaigns with no counters/warnings',
    status: 'PLACEHOLDER',
    routes: [],
    apiEndpoints: [],
    components: [],
    screenshotIds: [],
    notes: 'P0 — Conditional UI logic.',
    versionAdded: 'v2.0.0',
  },
  {
    id: 'B-USAGE-9',
    role: 'Brand',
    module: 'Usage Tracking & Limits',
    moduleCode: 'B-USAGE',
    story: 'Compact usage indicator in sidebar (progress bar or "15/20 searches")',
    status: 'PLACEHOLDER',
    routes: ['/brands/dashboard'],
    apiEndpoints: [],
    components: ['Sidebar', 'UsageMiniIndicator'],
    screenshotIds: ['SCR-B-USAGE-9'],
    notes: 'P1',
    versionAdded: 'v2.0.0',
  },
  {
    id: 'B-USAGE-10',
    role: 'Brand',
    module: 'Usage Tracking & Limits',
    moduleCode: 'B-USAGE',
    story: 'Server-side enforcement of all usage limits (middleware)',
    status: 'PLACEHOLDER',
    routes: [],
    apiEndpoints: [],
    components: [],
    screenshotIds: [],
    notes: 'P0 — Backend middleware. Critical security layer.',
    versionAdded: 'v2.0.0',
  },
  {
    id: 'B-USAGE-11',
    role: 'Brand',
    module: 'Usage Tracking & Limits',
    moduleCode: 'B-USAGE',
    story: 'Purchase search/campaign top-ups (overage packs)',
    status: 'PLACEHOLDER',
    routes: ['/brands/workspace/billing'],
    apiEndpoints: ['POST /api/subscriptions/{id}/top-up'],
    components: ['TopUpModal'],
    screenshotIds: ['SCR-B-USAGE-11'],
    notes: 'P2',
    versionAdded: 'v2.0.0',
  },
  {
    id: 'B-USAGE-12',
    role: 'Brand',
    module: 'Usage Tracking & Limits',
    moduleCode: 'B-USAGE',
    story: 'Monthly usage summary email',
    status: 'PLACEHOLDER',
    routes: [],
    apiEndpoints: [],
    components: [],
    screenshotIds: [],
    notes: 'P2 — Backend scheduled email.',
    versionAdded: 'v2.0.0',
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // PHASE 2: BRAND — Sharing & Viewer Access
  // ─────────────────────────────────────────────────────────────────────────────
  {
    id: 'B-SHARE-1',
    role: 'Brand',
    module: 'Sharing & Viewer Access',
    moduleCode: 'B-SHARE',
    story: 'Generate shareable read-only link for a specific campaign',
    status: 'PLACEHOLDER',
    routes: ['/brands/campaigns/[id]/dashboard'],
    apiEndpoints: ['POST /api/shared-links'],
    components: ['ShareModal', 'CopyLinkButton'],
    screenshotIds: ['SCR-B-SHARE-1'],
    notes: 'P0 — Enables virality and network effects.',
    versionAdded: 'v2.0.0',
  },
  {
    id: 'B-SHARE-2',
    role: 'Brand',
    module: 'Sharing & Viewer Access',
    moduleCode: 'B-SHARE',
    story: 'Viewer: branded read-only campaign view (no editing)',
    status: 'PLACEHOLDER',
    routes: ['/shared/[token]'],
    apiEndpoints: ['GET /api/shared-links/{token}'],
    components: ['SharedCampaignView'],
    screenshotIds: ['SCR-B-SHARE-2'],
    notes: 'P0',
    versionAdded: 'v2.0.0',
  },
  {
    id: 'B-SHARE-3',
    role: 'Brand',
    module: 'Sharing & Viewer Access',
    moduleCode: 'B-SHARE',
    story: 'Set expiry date on shared links (7d, 30d, custom, never)',
    status: 'PLACEHOLDER',
    routes: ['/brands/campaigns/[id]/dashboard'],
    apiEndpoints: ['POST /api/shared-links'],
    components: ['ShareModal'],
    screenshotIds: ['SCR-B-SHARE-3'],
    notes: 'P1',
    versionAdded: 'v2.0.0',
  },
  {
    id: 'B-SHARE-4',
    role: 'Brand',
    module: 'Sharing & Viewer Access',
    moduleCode: 'B-SHARE',
    story: 'Revoke shared link immediately',
    status: 'PLACEHOLDER',
    routes: ['/brands/workspace/settings'],
    apiEndpoints: ['DELETE /api/shared-links/{id}'],
    components: ['SharedLinksTable'],
    screenshotIds: ['SCR-B-SHARE-4'],
    notes: 'P0',
    versionAdded: 'v2.0.0',
  },
  {
    id: 'B-SHARE-5',
    role: 'Brand',
    module: 'Sharing & Viewer Access',
    moduleCode: 'B-SHARE',
    story: 'View all active shared links (creator, date, campaign, expiry)',
    status: 'PLACEHOLDER',
    routes: ['/brands/workspace/shared-links'],
    apiEndpoints: ['GET /api/workspaces/{id}/shared-links'],
    components: ['SharedLinksTable'],
    screenshotIds: ['SCR-B-SHARE-5'],
    notes: 'P1',
    versionAdded: 'v2.0.0',
  },
  {
    id: 'B-SHARE-6',
    role: 'Brand',
    module: 'Sharing & Viewer Access',
    moduleCode: 'B-SHARE',
    story: 'Viewer sees "Get your own workspace" CTA on shared views (virality)',
    status: 'PLACEHOLDER',
    routes: ['/shared/[token]'],
    apiEndpoints: [],
    components: ['SharedCampaignView', 'SignUpCTA'],
    screenshotIds: ['SCR-B-SHARE-6'],
    notes: 'P0 — Growth/virality engine.',
    versionAdded: 'v2.0.0',
  },
  {
    id: 'B-SHARE-7',
    role: 'Brand',
    module: 'Sharing & Viewer Access',
    moduleCode: 'B-SHARE',
    story: 'Invite external person as permanent Viewer (paid seat)',
    status: 'PLACEHOLDER',
    routes: ['/brands/workspace/team'],
    apiEndpoints: ['POST /api/workspaces/{id}/invitations'],
    components: ['InviteMemberModal'],
    screenshotIds: ['SCR-B-SHARE-7'],
    notes: 'P0',
    versionAdded: 'v2.0.0',
  },
  {
    id: 'B-SHARE-8',
    role: 'Brand',
    module: 'Sharing & Viewer Access',
    moduleCode: 'B-SHARE',
    story: 'Permanent Viewer: view-only dashboard with campaigns and analytics',
    status: 'PLACEHOLDER',
    routes: ['/brands/dashboard'],
    apiEndpoints: [],
    components: ['ViewerDashboard'],
    screenshotIds: ['SCR-B-SHARE-8'],
    notes: 'P0',
    versionAdded: 'v2.0.0',
  },
  {
    id: 'B-SHARE-9',
    role: 'Brand',
    module: 'Sharing & Viewer Access',
    moduleCode: 'B-SHARE',
    story: 'Share creator profile (read-only) with external link',
    status: 'PLACEHOLDER',
    routes: ['/brands/influencers/[id]'],
    apiEndpoints: ['POST /api/shared-links'],
    components: ['ShareModal'],
    screenshotIds: ['SCR-B-SHARE-9'],
    notes: 'P1',
    versionAdded: 'v2.0.0',
  },
  {
    id: 'B-SHARE-10',
    role: 'Brand',
    module: 'Sharing & Viewer Access',
    moduleCode: 'B-SHARE',
    story: 'Shared link analytics (views, viewers, timestamps)',
    status: 'PLACEHOLDER',
    routes: ['/brands/workspace/shared-links'],
    apiEndpoints: ['GET /api/shared-links/{id}/analytics'],
    components: ['SharedLinkAnalytics'],
    screenshotIds: ['SCR-B-SHARE-10'],
    notes: 'P2',
    versionAdded: 'v2.0.0',
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // PHASE 2: BRAND — Agency Management
  // ─────────────────────────────────────────────────────────────────────────────
  {
    id: 'B-AGENCY-1',
    role: 'Brand',
    module: 'Agency Management',
    moduleCode: 'B-AGENCY',
    story: 'Create multiple workspaces (one per brand client) from single account',
    status: 'PLACEHOLDER',
    routes: ['/brands/workspace/create'],
    apiEndpoints: ['POST /api/workspaces'],
    components: ['WorkspaceCreateWizard'],
    screenshotIds: ['SCR-B-AGENCY-1'],
    notes: 'P0',
    versionAdded: 'v2.0.0',
  },
  {
    id: 'B-AGENCY-2',
    role: 'Brand',
    module: 'Agency Management',
    moduleCode: 'B-AGENCY',
    story: 'Agency dashboard showing all workspaces with tier, usage, team size',
    status: 'PLACEHOLDER',
    routes: ['/brands/agency/dashboard'],
    apiEndpoints: ['GET /api/agency/overview'],
    components: ['AgencyDashboard', 'WorkspaceOverviewCard'],
    screenshotIds: ['SCR-B-AGENCY-2'],
    notes: 'P0',
    versionAdded: 'v2.0.0',
  },
  {
    id: 'B-AGENCY-3',
    role: 'Brand',
    module: 'Agency Management',
    moduleCode: 'B-AGENCY',
    story: 'Consolidated billing across all workspaces (one invoice)',
    status: 'PLACEHOLDER',
    routes: ['/brands/agency/billing'],
    apiEndpoints: ['GET /api/agency/billing'],
    components: ['ConsolidatedBillingPage'],
    screenshotIds: ['SCR-B-AGENCY-3'],
    notes: 'P1 — XL complexity.',
    versionAdded: 'v2.0.0',
  },
  {
    id: 'B-AGENCY-4',
    role: 'Brand',
    module: 'Agency Management',
    moduleCode: 'B-AGENCY',
    story: 'Assign different team members to different workspaces',
    status: 'PLACEHOLDER',
    routes: ['/brands/agency/team'],
    apiEndpoints: ['POST /api/workspaces/{id}/invitations'],
    components: ['AgencyTeamAssignment'],
    screenshotIds: ['SCR-B-AGENCY-4'],
    notes: 'P0',
    versionAdded: 'v2.0.0',
  },
  {
    id: 'B-AGENCY-5',
    role: 'Brand',
    module: 'Agency Management',
    moduleCode: 'B-AGENCY',
    story: 'Set different subscription tiers per workspace',
    status: 'PLACEHOLDER',
    routes: ['/brands/agency/billing'],
    apiEndpoints: ['POST /api/subscriptions'],
    components: ['PerWorkspacePlanSelector'],
    screenshotIds: ['SCR-B-AGENCY-5'],
    notes: 'P0',
    versionAdded: 'v2.0.0',
  },
  {
    id: 'B-AGENCY-6',
    role: 'Brand',
    module: 'Agency Management',
    moduleCode: 'B-AGENCY',
    story: 'Team member sees only assigned workspaces (not all agency workspaces)',
    status: 'PLACEHOLDER',
    routes: ['/brands/dashboard'],
    apiEndpoints: ['GET /api/workspaces'],
    components: ['WorkspaceSwitcher'],
    screenshotIds: ['SCR-B-AGENCY-6'],
    notes: 'P0',
    versionAdded: 'v2.0.0',
  },
  {
    id: 'B-AGENCY-7',
    role: 'Brand',
    module: 'Agency Management',
    moduleCode: 'B-AGENCY',
    story: 'Bulk-create workspaces (import brand list from CSV)',
    status: 'PLACEHOLDER',
    routes: ['/brands/agency/import'],
    apiEndpoints: ['POST /api/agency/bulk-create'],
    components: ['BulkImportWizard'],
    screenshotIds: ['SCR-B-AGENCY-7'],
    notes: 'P2',
    versionAdded: 'v2.0.0',
  },
  {
    id: 'B-AGENCY-8',
    role: 'Brand',
    module: 'Agency Management',
    moduleCode: 'B-AGENCY',
    story: 'Cross-workspace analytics (compare performance across brands)',
    status: 'PLACEHOLDER',
    routes: ['/brands/agency/analytics'],
    apiEndpoints: ['GET /api/agency/analytics'],
    components: ['CrossWorkspaceAnalytics'],
    screenshotIds: ['SCR-B-AGENCY-8'],
    notes: 'P2 — XL complexity.',
    versionAdded: 'v2.0.0',
  },
  {
    id: 'B-AGENCY-9',
    role: 'Brand',
    module: 'Agency Management',
    moduleCode: 'B-AGENCY',
    story: 'Set agency-wide brand kit (logo, colours) across all workspaces',
    status: 'PLACEHOLDER',
    routes: ['/brands/agency/settings'],
    apiEndpoints: ['PATCH /api/agency/brand-kit'],
    components: ['AgencyBrandKitEditor'],
    screenshotIds: ['SCR-B-AGENCY-9'],
    notes: 'P2',
    versionAdded: 'v2.0.0',
  },
  {
    id: 'B-AGENCY-10',
    role: 'Brand',
    module: 'Agency Management',
    moduleCode: 'B-AGENCY',
    story: 'Volume discount applied automatically for 3+ workspaces',
    status: 'PLACEHOLDER',
    routes: ['/brands/agency/billing'],
    apiEndpoints: [],
    components: ['VolumeDiscountBadge'],
    screenshotIds: ['SCR-B-AGENCY-10'],
    notes: 'P1',
    versionAdded: 'v2.0.0',
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // PHASE 2: SHARED — Migration & Onboarding
  // ─────────────────────────────────────────────────────────────────────────────
  {
    id: 'S-MIGR-1',
    role: 'Shared',
    module: 'Migration & Onboarding',
    moduleCode: 'S-MIGR',
    story: 'Existing Phase 1 user guided through migration wizard to create first workspace',
    status: 'PLACEHOLDER',
    routes: ['/migration/welcome'],
    apiEndpoints: ['POST /api/migration/start'],
    components: ['MigrationWizard'],
    screenshotIds: ['SCR-S-MIGR-1-S1', 'SCR-S-MIGR-1-S2', 'SCR-S-MIGR-1-SUCCESS'],
    notes: 'P0 — XL. Critical for existing user retention.',
    versionAdded: 'v2.0.0',
  },
  {
    id: 'S-MIGR-2',
    role: 'Shared',
    module: 'Migration & Onboarding',
    moduleCode: 'S-MIGR',
    story: 'Existing campaigns automatically moved into new workspace',
    status: 'PLACEHOLDER',
    routes: [],
    apiEndpoints: ['POST /api/migration/start'],
    components: [],
    screenshotIds: [],
    notes: 'P0 — Backend migration logic.',
    versionAdded: 'v2.0.0',
  },
  {
    id: 'S-MIGR-3',
    role: 'Shared',
    module: 'Migration & Onboarding',
    moduleCode: 'S-MIGR',
    story: 'Saved creator lists and notes moved into new workspace',
    status: 'PLACEHOLDER',
    routes: [],
    apiEndpoints: ['POST /api/migration/start'],
    components: [],
    screenshotIds: [],
    notes: 'P0 — Backend migration logic.',
    versionAdded: 'v2.0.0',
  },
  {
    id: 'S-MIGR-4',
    role: 'Shared',
    module: 'Migration & Onboarding',
    moduleCode: 'S-MIGR',
    story: 'New user streamlined flow: create account → workspace → plan → invite team',
    status: 'PLACEHOLDER',
    routes: ['/auth/brand/signup/account', '/brands/workspace/create'],
    apiEndpoints: ['POST /api/workspaces'],
    components: ['WorkspaceCreateWizard'],
    screenshotIds: ['SCR-S-MIGR-4'],
    notes: 'P0',
    versionAdded: 'v2.0.0',
  },
  {
    id: 'S-MIGR-5',
    role: 'Shared',
    module: 'Migration & Onboarding',
    moduleCode: 'S-MIGR',
    story: 'Admin: batch migration for all existing Phase 1 users',
    status: 'PLACEHOLDER',
    routes: ['/admin/migration'],
    apiEndpoints: ['POST /api/admin/migration/batch'],
    components: ['MigrationAdminPanel'],
    screenshotIds: ['SCR-S-MIGR-5'],
    notes: 'P0',
    versionAdded: 'v2.0.0',
  },
  {
    id: 'S-MIGR-6',
    role: 'Shared',
    module: 'Migration & Onboarding',
    moduleCode: 'S-MIGR',
    story: 'Interactive product tour (tooltips) on first workspace visit',
    status: 'PLACEHOLDER',
    routes: ['/brands/dashboard'],
    apiEndpoints: [],
    components: ['ProductTour', 'TooltipOverlay'],
    screenshotIds: ['SCR-S-MIGR-6'],
    notes: 'P1',
    versionAdded: 'v2.0.0',
  },
  {
    id: 'S-MIGR-7',
    role: 'Shared',
    module: 'Migration & Onboarding',
    moduleCode: 'S-MIGR',
    story: 'Sample/demo data in new workspace for exploration',
    status: 'PLACEHOLDER',
    routes: ['/brands/dashboard'],
    apiEndpoints: ['POST /api/workspaces/{id}/seed-demo'],
    components: [],
    screenshotIds: ['SCR-S-MIGR-7'],
    notes: 'P2',
    versionAdded: 'v2.0.0',
  },
  {
    id: 'S-MIGR-8',
    role: 'Shared',
    module: 'Migration & Onboarding',
    moduleCode: 'S-MIGR',
    story: 'Influencer experience unchanged — workspaces are brand-side only',
    status: 'PLACEHOLDER',
    routes: [],
    apiEndpoints: [],
    components: [],
    screenshotIds: [],
    notes: 'P0 — Validation/testing story.',
    versionAdded: 'v2.0.0',
  },
  {
    id: 'S-MIGR-9',
    role: 'Shared',
    module: 'Migration & Onboarding',
    moduleCode: 'S-MIGR',
    story: 'Migration complete confirmation showing what was moved',
    status: 'PLACEHOLDER',
    routes: ['/migration/complete'],
    apiEndpoints: [],
    components: ['MigrationCompleteScreen'],
    screenshotIds: ['SCR-S-MIGR-9'],
    notes: 'P1',
    versionAdded: 'v2.0.0',
  },
  {
    id: 'S-MIGR-10',
    role: 'Shared',
    module: 'Migration & Onboarding',
    moduleCode: 'S-MIGR',
    story: 'Admin: migration rollback capability for 30 days post-migration',
    status: 'PLACEHOLDER',
    routes: ['/admin/migration'],
    apiEndpoints: ['POST /api/admin/migration/{userId}/rollback'],
    components: ['MigrationAdminPanel'],
    screenshotIds: ['SCR-S-MIGR-10'],
    notes: 'P1',
    versionAdded: 'v2.0.0',
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // PHASE 2: BRAND — Trial & Free Tier
  // ─────────────────────────────────────────────────────────────────────────────
  {
    id: 'B-TRIAL-1',
    role: 'Brand',
    module: 'Trial & Free Tier',
    moduleCode: 'B-TRIAL',
    story: '14-day free trial of Growth plan (no credit card required)',
    status: 'PLACEHOLDER',
    routes: ['/brands/workspace/create'],
    apiEndpoints: ['POST /api/subscriptions/trial'],
    components: ['TrialBanner'],
    screenshotIds: ['SCR-B-TRIAL-1'],
    notes: 'P0 — Critical for user acquisition.',
    versionAdded: 'v2.0.0',
  },
  {
    id: 'B-TRIAL-2',
    role: 'Brand',
    module: 'Trial & Free Tier',
    moduleCode: 'B-TRIAL',
    story: 'Trial countdown banner (X days remaining) with Subscribe CTA',
    status: 'PLACEHOLDER',
    routes: ['/brands/dashboard'],
    apiEndpoints: [],
    components: ['TrialCountdownBanner'],
    screenshotIds: ['SCR-B-TRIAL-2'],
    notes: 'P0',
    versionAdded: 'v2.0.0',
  },
  {
    id: 'B-TRIAL-3',
    role: 'Brand',
    module: 'Trial & Free Tier',
    moduleCode: 'B-TRIAL',
    story: 'Expired trial → workspace enters read-only mode',
    status: 'PLACEHOLDER',
    routes: ['/brands/dashboard'],
    apiEndpoints: [],
    components: ['ReadOnlyBanner'],
    screenshotIds: ['SCR-B-TRIAL-3'],
    notes: 'P0',
    versionAdded: 'v2.0.0',
  },
  {
    id: 'B-TRIAL-4',
    role: 'Brand',
    module: 'Trial & Free Tier',
    moduleCode: 'B-TRIAL',
    story: 'Convert trial to paid plan at any time',
    status: 'PLACEHOLDER',
    routes: ['/brands/workspace/billing'],
    apiEndpoints: ['POST /api/subscriptions/convert-trial'],
    components: ['ConvertTrialModal'],
    screenshotIds: ['SCR-B-TRIAL-4'],
    notes: 'P0',
    versionAdded: 'v2.0.0',
  },
  {
    id: 'B-TRIAL-5',
    role: 'Brand',
    module: 'Trial & Free Tier',
    moduleCode: 'B-TRIAL',
    story: 'Email nudges at day 7, 12, and 14 (expiry)',
    status: 'PLACEHOLDER',
    routes: [],
    apiEndpoints: [],
    components: [],
    screenshotIds: [],
    notes: 'P1 — Backend scheduled emails.',
    versionAdded: 'v2.0.0',
  },
  {
    id: 'B-TRIAL-6',
    role: 'Brand',
    module: 'Trial & Free Tier',
    moduleCode: 'B-TRIAL',
    story: 'Admin: trial conversion analytics (signups, conversions, churn)',
    status: 'PLACEHOLDER',
    routes: ['/admin/analytics'],
    apiEndpoints: ['GET /api/admin/trial-analytics'],
    components: ['TrialAnalyticsDashboard'],
    screenshotIds: ['SCR-B-TRIAL-6'],
    notes: 'P2',
    versionAdded: 'v2.0.0',
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // PHASE 2: SHARED — Legal & Compliance
  // ─────────────────────────────────────────────────────────────────────────────
  {
    id: 'S-LEGAL-1',
    role: 'Shared',
    module: 'Legal & Compliance',
    moduleCode: 'S-LEGAL',
    story: 'Accept Terms of Service and Data Processing Agreement per workspace',
    status: 'PLACEHOLDER',
    routes: ['/brands/workspace/create'],
    apiEndpoints: ['POST /api/legal/accept'],
    components: ['ToSAcceptanceModal'],
    screenshotIds: ['SCR-S-LEGAL-1'],
    notes: 'P0',
    versionAdded: 'v2.0.0',
  },
  {
    id: 'S-LEGAL-2',
    role: 'Shared',
    module: 'Legal & Compliance',
    moduleCode: 'S-LEGAL',
    story: 'Export all personal data (POPIA/GDPR compliance)',
    status: 'PLACEHOLDER',
    routes: ['/brands/workspace/settings'],
    apiEndpoints: ['GET /api/workspaces/{id}/export'],
    components: ['DataExportButton'],
    screenshotIds: ['SCR-S-LEGAL-2'],
    notes: 'P0 — Required by South African law (POPIA).',
    versionAdded: 'v2.0.0',
  },
  {
    id: 'S-LEGAL-3',
    role: 'Shared',
    module: 'Legal & Compliance',
    moduleCode: 'S-LEGAL',
    story: 'Request account and data deletion (right to be forgotten)',
    status: 'PLACEHOLDER',
    routes: ['/brands/workspace/settings'],
    apiEndpoints: ['POST /api/legal/deletion-request'],
    components: ['DeletionRequestModal'],
    screenshotIds: ['SCR-S-LEGAL-3'],
    notes: 'P0',
    versionAdded: 'v2.0.0',
  },
  {
    id: 'S-LEGAL-4',
    role: 'Shared',
    module: 'Legal & Compliance',
    moduleCode: 'S-LEGAL',
    story: 'Admin: record of all ToS/DPA acceptances (who, when, version)',
    status: 'PLACEHOLDER',
    routes: ['/admin/legal'],
    apiEndpoints: ['GET /api/admin/legal/acceptances'],
    components: ['LegalAcceptancesTable'],
    screenshotIds: ['SCR-S-LEGAL-4'],
    notes: 'P0',
    versionAdded: 'v2.0.0',
  },
  {
    id: 'S-LEGAL-5',
    role: 'Shared',
    module: 'Legal & Compliance',
    moduleCode: 'S-LEGAL',
    story: 'Audit log of all member actions (login, changes, exports)',
    status: 'PLACEHOLDER',
    routes: ['/brands/workspace/audit-log'],
    apiEndpoints: ['GET /api/workspaces/{id}/audit-log'],
    components: ['AuditLogTable'],
    screenshotIds: ['SCR-S-LEGAL-5'],
    notes: 'P2',
    versionAdded: 'v2.0.0',
  },
  {
    id: 'S-LEGAL-6',
    role: 'Shared',
    module: 'Legal & Compliance',
    moduleCode: 'S-LEGAL',
    story: 'Admin: force ToS re-acceptance when terms change',
    status: 'PLACEHOLDER',
    routes: [],
    apiEndpoints: ['POST /api/admin/legal/force-reaccept'],
    components: ['ToSReacceptBanner'],
    screenshotIds: ['SCR-S-LEGAL-6'],
    notes: 'P1',
    versionAdded: 'v2.0.0',
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// Helper utilities
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Returns all stories belonging to a given module code (e.g. 'B-AUTH', 'I-CAMP').
 */
export const getStoriesByModule = (moduleCode: string): UserStory[] =>
  STORIES.filter((s) => s.moduleCode === moduleCode);

/**
 * Returns all stories belonging to a given role ('Brand', 'Influencer', or 'Shared').
 */
export const getStoriesByRole = (role: StoryRole): UserStory[] =>
  STORIES.filter((s) => s.role === role);
